/* Contenido — Escudo Digital · She Is Foundation · SESIÓN 3 (1 hora).
 *
 * Motor en ../../_base. De este archivo salen las slides, la vista presentador,
 * el guion (node ../../_base/herramientas/guion.mjs) y la guía.
 *
 * Adaptado del taller de Fundasol (2 h) a 1 hora:
 *   - La sesión 2 de She Is fue PHISHING: lo de enlaces y correos trampa no se
 *     repite; solo entra como repaso corto (repaso, bandeja de alias).
 *   - El grupo participa poco: más slides con menos conversación. Si nadie
 *     responde, se revela y se sigue.
 *   - Sin pausa, sin buzón y sin «Mi plan de guardiana» en papel: el plan y las
 *     rutas de menús van en la guía PDF.
 *
 * Votación sin materiales: 1, 2 o 3 dedos. Sin dispositivos: maquetas en pantalla.
 */

globalThis.META = {
  titulo: "Escudo Digital",
  subtitulo: "Sesión 3 · Herramientas de guardiana — She Is Foundation",
  organiza: "She Is",
  apoya: "Sapientiam · ETITC",
  presupuesto: 60,
  bloques: {
    1: "Bloque 1 · Lo que no se ve",
    2: "Bloque 2 · Trucos de guardiana",
  },
  contacto: { nombre: "She Is Foundation", whatsapp: "+57 310 785 9540", correo: "info@she-is.org" },
  logos: [
    { src: "../img/she-is.png", nombre: "She Is Foundation", alto: 13 },
    { src: "../../_base/img/sapientiam.png", nombre: "Semillero<br>Sapientiam", oscuro: true },
    { src: "../../_base/img/etitc.png", nombre: "Escuela Tecnológica Instituto Técnico Central", alto: 9 },
  ],
  contexto: [
    "**Es la sesión 3 de She Is.** La sesión 2 fue phishing: no volver a explicarlo, solo conectarlo (repaso y bandeja de alias).",
    "**La sesión 1 fue «Tu identidad es única»**: ya saben qué datos no se publican y reconocer un perfil falso. Aquí se pasa de reconocer a las herramientas (foto detective, ajustes, reportar la suplantación, Google Lens).",
    "**1 hora, sin pausa.** El grupo participa poco: preguntar, esperar 5 segundos y, si nadie responde, revelar y seguir.",
    "Sin dispositivos: toda la práctica es con maquetas en pantalla. Las rutas de menús y el plan quedan en la guía PDF.",
  ],
  quienOrganiza: "She Is Foundation",
  materiales: [
    "Computador + proyector (o TV) + extensión de pantalla, no espejo.",
    "Mandar la guía PDF a las familias después del taller.",
    "Revisar antes los menús de Instagram, TikTok, WhatsApp y Roblox: cambian con las actualizaciones.",
  ],
};

globalThis.SLIDES = [
  /* ═══════════════════════ BLOQUE 1 ═══════════════════════ */
  {
    id: "portada",
    bloque: 1,
    tema: "violeta",
    min: 0,
    tipo: "portada",
    titulo: "Escudo Digital",
    bajada: "Tercera misión: de reconocer a protegerte",
    nota: [
      "Mientras entran: esta slide en pantalla.",
      "Bienvenida. Es la tercera sesión: «la vez pasada aprendimos a reconocer el phishing; hoy vamos a aprender a protegernos con herramientas de verdad».",
      "Dos partes: primero lo que no se ve (lo que revelamos sin darnos cuenta y las trampas nuevas), después trucos prácticos de guardiana.",
    ],
  },
  {
    id: "lumi",
    bloque: 1,
    tema: "amarillo",
    min: 1,
    tipo: "mensaje",
    lumiGrande: "hola",
    titulo: "¡Hola! Soy Lumi",
    bajada: "Hoy votamos con los dedos",
    chips: [
      { e: "☝️", t: "1 dedo" },
      { e: "✌️", t: "2 dedos" },
      { e: "🤟", t: "3 dedos" },
    ],
    nota: [
      "Lumi ya la conocen de las sesiones 1 y 2: saludarla como a una vieja amiga.",
      "Cómo votamos: cuando haya opciones 1, 2 o 3, levantan esa cantidad de dedos. Practicar: «¿quién vino a la sesión pasada? Un dedo sí, dos dedos no».",
      "Si hay niñas que no vinieron a las sesiones anteriores, no pasa nada: el repaso de la siguiente slide las pone al día.",
    ],
    preguntar: ["¿Quién vino a la sesión pasada? ☝️ sí · ✌️ no"],
  },
  {
    id: "repaso",
    bloque: 1,
    tema: "coral",
    min: 2,
    tipo: "pregunta",
    eyebrow: "Repaso relámpago",
    situacion: "«🚨 Tu cuenta será eliminada. Tienes 10 minutos. Mándame el código que te llegó».",
    titulo: "¿Qué aprendimos a hacer?",
    opciones: ["Mandar el código rápido", "Para, piensa, verifica", "Reenviarlo a mis amigas"],
    correcta: 1,
    explica: "Si te apuran, asustan o emocionan: detente.",
    nota: [
      "Repaso de la sesión de phishing: activa lo que ya saben sin volver a explicarlo. Máximo 1 minuto.",
      "Si nadie responde (este grupo participa poco), no esperar: revelar y decir la regla en voz alta. PARA · PIENSA · VERIFICA.",
      "Puente: «ya saben reconocer las trampas. Hoy vamos un paso más allá: qué revelamos sin darnos cuenta y qué herramientas tenemos».",
    ],
    respuesta: "2 · Para, piensa, verifica.",
  },
  {
    id: "acuerdos",
    bloque: 1,
    tema: "rosa",
    min: 4,
    tipo: "tarjetas",
    titulo: "Nuestros acuerdos",
    items: [
      { e: "🤫", k: "Lo que se dice aquí", v: "se queda aquí" },
      { e: "🙊", k: "Sin nombres reales", v: "decimos «una amiga»" },
      { e: "💜", k: "No hay preguntas tontas", v: "todas valen" },
      { e: "✋", k: "Puedo pasar", v: "si no quiero hablar" },
    ],
    nota: [
      "Leer cada acuerdo y pedir un pulgar arriba.",
      "PROTOCOLO: si una niña cuenta algo que suena a riesgo real (acoso fuerte, alguien que le ofrece dinero o encuentros, amenazas), NO profundizar frente al grupo. Agradecer, decir «hablemos al final» y hacerlo en privado. Luego informar a quien organiza para activar la ruta (orientación del colegio, Línea 141 ICBF, 123 si hay peligro inmediato).",
    ],
  },
  {
    id: "hoy",
    bloque: 1,
    tema: "turquesa",
    min: 5,
    tipo: "mensaje",
    emoji: "🧰",
    titulo: "Hoy: herramientas de guardiana",
    chips: [
      { e: "🔍", t: "Lo que revelas" },
      { e: "🚫", t: "Ofertas trampa" },
      { e: "🙈", t: "Poderes secretos" },
      { e: "📧", t: "Alias" },
      { e: "🎮", t: "Juegos" },
    ],
    revelar: true,
    nota: [
      "Mapa de la sesión. Revelar un chip por clic y decir una frase de cada uno.",
      "Generar expectativa con los alias: «les voy a enseñar un truco de correo que casi ningún adulto conoce».",
    ],
  },
  {
    id: "foto-detective",
    bloque: 1,
    tema: "violeta",
    min: 6,
    tipo: "publicacion",
    titulo: "¿Qué sabe un extraño de esta foto?",
    usuario: "vale.dibuja",
    lugar: "📍 Parque El Tunal",
    escena: ["🌳", "👧🏽", "🏫", "🐶", "🏠"],
    texto: "Saliendo del cole como todos los días a las 3 😎 con Lupe 🐶",
    pistas: [
      { t: "Uniforme y escudo: dónde estudias", x: 36, y: 44 },
      { t: "Ubicación etiquetada", x: 70, y: 9 },
      { t: "Rutina: todos los días a las 3", x: 88, y: 88 },
      { t: "Fachada y número de tu casa", x: 82, y: 48 },
      { t: "Nombre de tu mascota: ¡pregunta de seguridad!", x: 60, y: 62 },
    ],
    nota: [
      "Actividad de detective. Ellas dicen qué pistas ven; por cada una, clic y aparece el pin.",
      "Con estas 5 pistas, un desconocido sabe dónde estudias, a qué hora sales, por dónde pasas y dónde vives. Nadie te preguntó nada: lo publicaste tú.",
      "La mascota sorprende: muchas cuentas usan «¿nombre de tu primera mascota?» para recuperar la contraseña.",
    ],
    preguntar: ["¿Qué sabe de ti alguien que ve solo esta foto?"],
    respuesta: "Colegio (uniforme), ubicación, horario, dónde vive (fachada), nombre de la mascota.",
  },
  {
    id: "antes-de-publicar",
    bloque: 1,
    tema: "amarillo",
    min: 10,
    tipo: "tarjetas",
    titulo: "Antes de publicar, revisa",
    revelar: true,
    items: [
      { e: "👕", k: "Uniforme", v: "sin escudo ni nombre del colegio" },
      { e: "📍", k: "Ubicación", v: "apagada, nunca en vivo" },
      { e: "⏰", k: "Publica después", v: "cuando ya te fuiste" },
      { e: "🏠", k: "El fondo", v: "sin fachada, placas ni direcciones" },
      { e: "🔁", k: "Sin rutinas", v: "no digas «todos los días»" },
    ],
    nota: [
      "No se trata de dejar de publicar, sino de publicar sin regalar el mapa.",
      "La idea más útil: publicar DESPUÉS. La foto del parque se sube cuando ya estás en casa.",
      "Las historias «en vivo» con ubicación son las más riesgosas: dicen dónde estás ahora mismo.",
    ],
    preguntar: ["¿Cuál de estas nunca habías pensado?"],
  },
  {
    id: "ofertas",
    bloque: 1,
    tema: "noche",
    min: 12,
    tipo: "mensaje",
    emoji: "🎁",
    titulo: "Ofertas demasiado buenas",
    bajada: "Una trampa nueva que está pasando cerca",
    lumi: { pose: "alerta", t: "¡Ojos de búha!" },
    nota: [
      "Cambio de tono: la slide se oscurece a propósito.",
      "Presentar el caso como ficticio pero basado en algo real que está pasando en Bogotá.",
      "Hablar despacio y sin dramatismo: el objetivo es que reconozcan el patrón, no asustarlas.",
    ],
  },
  {
    id: "oferta-belleza",
    bloque: 1,
    tema: "noche",
    min: 13,
    tipo: "chat",
    titulo: "Caso: la oferta de belleza",
    bajada: "Encuentra las 🚩",
    contacto: { nombre: "glow.studio.bog ✨", e: "💇‍♀️" },
    mensajes: [
      { t: "Hola linda 💕 buscamos niñas para una campaña de cabello", pista: "Te buscan sin conocerte" },
      { t: "Te pagamos $100.000 y las uñas gratis 💅", pista: "Dinero fácil" },
      { t: "Es HOY, los cupos se acaban 🔥", pista: "Prisa" },
      { t: "Ven sola, es rapidito, no traigas a nadie", pista: "¡Que vayas SOLA!" },
      { t: "No le digas a tu mamá, es sorpresa 🤫 ¿En qué barrio vives?", pista: "Secreto + dónde vives" },
    ],
    nota: [
      "CASO FICTICIO basado en una modalidad real reportada en Bogotá en septiembre de 2026: a niñas y adolescentes les ofrecían por redes sociales dinero por cortarse el cabello y hacerse las uñas, y terminaban retenidas.",
      "Leer el chat completo. Por cada alarma que identifiquen, clic y aparece la bandera.",
      "Las dos más graves: que vayas SOLA y que no le cuentes a tu familia. Una oferta de trabajo o belleza de verdad nunca pide eso, y menos a una menor de edad.",
      "Conectar con el phishing: es el mismo patrón (prisa, secreto, algo demasiado bueno) pero ahora no busca tu clave sino que vayas a un lugar.",
    ],
    preguntar: ["¿Qué pista te parece más peligrosa?", "¿Qué haría una empresa de verdad?"],
    respuesta: "Las 5 son alertas. Una empresa real habla con tus papás, no te apura, no te pide ir sola ni guardar secretos.",
  },
  {
    id: "dato-real",
    bloque: 1,
    tema: "noche",
    min: 17,
    tipo: "dato",
    cifra: "334",
    titulo: "niñas de 10 a 17 años",
    bajada: "fueron reportadas como desaparecidas en Bogotá entre enero y junio de 2026",
    detalle: "A muchas las contactan por redes con ofertas de dinero, belleza o trabajo.",
    fuente: "Policía Nacional y Medicina Legal, vía Semana (15-09-2026) · Noticias RCN (16-09-2026)",
    nota: [
      "Leer la cifra y dejar un silencio.",
      "Contexto para quien facilita: en el mismo periodo se reportaron 144 víctimas de trata en Bogotá, más del doble que en 2025. La cifra de 334 es de reportes de desaparición: muchas niñas aparecen, pero cada caso se toma en serio.",
      "Cerrar con poder, no con miedo: «esto no significa que no puedan salir o usar redes. Significa que ahora saben reconocer la trampa y tienen reglas para protegerse. Vamos a verlas».",
      "Si alguna se ve afectada o menciona un caso cercano: protocolo de la slide de acuerdos.",
    ],
  },
  {
    id: "regla-encuentros",
    bloque: 1,
    tema: "amarillo",
    min: 19,
    tipo: "regla",
    titulo: "La regla de los encuentros",
    pasos: [
      { e: "🙅‍♀️", k: "NUNCA SOLA", v: "con alguien de internet" },
      { e: "🗣️", k: "TU ADULTO", v: "sabe y te acompaña" },
      { e: "📍", k: "UBICACIÓN", v: "compartida con tu familia" },
      { e: "🔑", k: "PALABRA CLAVE", v: "secreta, en familia" },
    ],
    nota: [
      "Revelar una por una.",
      "Ubicación en tiempo real: WhatsApp y los celulares permiten compartirla con tu mamá o papá mientras vas a algún lado.",
      "Palabra clave familiar: una palabra secreta que solo sabe tu familia. Si alguien dice «tu mamá me mandó a recogerte», le pides la palabra. Si no la sabe, no vas. Proponer que la acuerden esta semana en casa (sin decirla aquí).",
      "Tarea para la casa: acordar la palabra clave. Queda en la guía que se llevan.",
    ],
    preguntar: ["¿Qué palabra clave sería difícil de adivinar? (no la digan en voz alta)"],
  },
  {
    id: "oferta-o-trampa",
    bloque: 1,
    tema: "coral",
    min: 22,
    tipo: "semaforo",
    titulo: "¿Oferta o trampa?",
    items: [
      { t: "Tu tía te lleva a cortarte el cabello a su peluquería", color: "verde" },
      { t: "Una marca que sigues sortea un premio: solo hay que seguirla", color: "amarillo" },
      { t: "Te ofrecen dinero por fotos o videos tuyos", color: "rojo" },
      { t: "Una «agencia» te invita a un casting: ve sola", color: "rojo" },
      { t: "Te ofrecen trabajo fácil por mensaje directo", color: "rojo" },
      { t: "Te regalan recargas si se ven en persona", color: "rojo" },
    ],
    nota: [
      "Leer cada situación, que digan el color en voz alta, clic para revelar.",
      "El sorteo es amarillo: puede ser real, pero verifica que sea la cuenta oficial y nunca des datos personales, dirección ni contraseñas para «reclamar el premio».",
      "Regla simple: si la oferta involucra dinero, tu cuerpo, tu imagen o encontrarse en persona, es rojo hasta que un adulto lo revise.",
    ],
    respuesta: "🟢 · 🟡 · 🔴 · 🔴 · 🔴 · 🔴",
  },
  {
    id: "poderes-instagram",
    bloque: 1,
    tema: "turquesa",
    min: 25,
    tipo: "app",
    titulo: "Poderes que casi nadie usa",
    app: "Instagram · TikTok",
    pasos: [
      { e: "🙈", k: "Restringir", v: "no sabe que lo hiciste; sus comentarios solo los ve él" },
      { e: "🔤", k: "Palabras ocultas", v: "esconde comentarios con insultos" },
      { e: "🚧", k: "Limitar", v: "frena un ataque por unos días" },
      { e: "🏷️", k: "Etiquetas y menciones", v: "solo personas que sigues" },
      { e: "🔇", k: "Silenciar", v: "dejas de verlo sin que se entere" },
    ],
    nota: [
      "Cada clic enciende un interruptor en el celular de la pantalla.",
      "⚠️ Los menús cambian con cada actualización. Recorrer las cinco rutas en un celular real la semana del taller y corregir aquí lo que se haya movido. En Instagram casi todas viven en el mismo sitio: Configuración y privacidad → «Cómo pueden interactuar otras personas contigo».",
      "1 · RESTRINGIR (Instagram). Para qué: el acosador es del salón y bloquearlo lo empeora, porque se da cuenta. Qué le pasa a él: sus comentarios solo los ve él, sus mensajes caen en solicitudes y deja de ver si estás en línea. Ruta corta: entrar a su perfil → ⋯ (arriba a la derecha) → Restringir. Ruta por ajustes: Configuración y privacidad → Cómo pueden interactuar otras personas contigo → Cuentas restringidas.",
      "2 · PALABRAS OCULTAS (Instagram). Ruta: Configuración y privacidad → Cómo pueden interactuar otras personas contigo → Palabras ocultas. Activar «Ocultar comentarios ofensivos» y, más abajo, «Palabras y frases personalizadas»: ahí escriben sus propios apodos ofensivos, separados por comas. Vale también para las solicitudes de mensajes. En TikTok: Configuración y privacidad → Privacidad → Comentarios → Filtrar palabras clave.",
      "3 · LIMITAR (Instagram). Para qué: de un día para otro llegan muchos comentarios y mensajes de cuentas desconocidas. Ruta: Configuración y privacidad → Cómo pueden interactuar otras personas contigo → Limitar interacciones → escoger «cuentas que no te siguen» y/o «cuentas nuevas», y por cuánto tiempo. Es temporal: se apaga solo.",
      "4 · ETIQUETAS Y MENCIONES (Instagram). Ruta: Configuración y privacidad → Cómo pueden interactuar otras personas contigo → Etiquetas y menciones → dejar las dos en «Personas a las que sigues». En TikTok: Privacidad → Menciones y etiquetas. Extra de TikTok: Privacidad → Dúo y Privacidad → Stitch, para que nadie use sus videos.",
      "5 · SILENCIAR (Instagram). Para qué: no quieres verla, pero no quieres bloquear. Ruta: su perfil → botón «Siguiendo» → Silenciar → publicaciones e historias. Ella no se entera nunca.",
      "Cerrar sin agobiar: no hay que activar las cinco hoy. Cada una elige UNA para esta semana; las rutas quedan en la guía.",
    ],
    preguntar: ["¿Cuándo sería mejor restringir que bloquear?"],
    respuesta: "Cuando bloquear haría que la persona se dé cuenta y lo empeore (por ejemplo, alguien del salón).",
  },
  {
    id: "captura",
    bloque: 1,
    tema: "violeta",
    min: 29,
    tipo: "pregunta",
    eyebrow: "Quiz",
    situacion: "Alguien te insulta en un comentario. Quieres guardar la prueba.",
    titulo: "¿Qué captura sirve?",
    opciones: ["Solo el insulto, recortado", "Usuario + fecha + mensaje completo", "Le cuento a mi amiga qué decía"],
    correcta: 1,
    explica: "Captura que sirve = quién · cuándo · qué dijo.",
    nota: [
      "Antes de bloquear o reportar, se guarda la evidencia. Y hay que hacerla bien.",
      "Una captura recortada no sirve: no se sabe quién lo dijo ni cuándo. Debe verse el nombre de usuario (idealmente abrir el perfil y capturarlo también), la fecha y el mensaje completo.",
      "Tips: capturar ANTES de bloquear (después ya no se ve), guardar las capturas en una carpeta, y si es posible copiar el enlace del perfil.",
    ],
    respuesta: "2 · Usuario + fecha + mensaje completo.",
  },
  {
    id: "suplantacion",
    bloque: 1,
    tema: "coral",
    min: 31,
    tipo: "escenario",
    eyebrow: "¿Qué harías tú?",
    titulo: "Una cuenta falsa con tu nombre",
    situacion: "Aparece @vale.dibuja_ con tus fotos. Le escribe cosas feas a tus amigas como si fueras tú.",
    opciones: [
      { t: "Le escribo a la cuenta falsa para que la borre", pasa: "No la borra y ahora sabe que te afecta 😟" },
      { t: "Me creo otra cuenta para contestarle", pasa: "Ahora hay tres cuentas peleando 🔥" },
      { t: "Capturas, la reporto como suplantación, aviso que no soy yo y le cuento a un adulto", pasa: "Tus amigas la reportan contigo y la app la baja 💪", ok: true },
    ],
    nota: [
      "Suplantación: alguien se hace pasar por ti. Hoy vemos cómo se soluciona.",
      "Pasos: 1) capturas del perfil falso y de los mensajes, 2) reportar la cuenta con la opción «se hace pasar por mí» (las apps tienen esa opción específica), 3) pedir a amigas y familia que también la reporten, 4) publicar en tu cuenta real «esa cuenta no soy yo», 5) contárselo a un adulto.",
      "Si publica fotos íntimas o amenazas, es delito: se denuncia en el CAI Virtual.",
    ],
    preguntar: ["¿Quién más puede ayudarte a reportarla?"],
    respuesta: "3 · Capturas, reportar como suplantación, avisar que no eres tú, contarle a un adulto.",
  },
  /* ═══════════════════════ BLOQUE 2 ═══════════════════════ */
  {
    id: "alias",
    bloque: 2,
    tema: "turquesa",
    min: 34,
    tipo: "alias",
    titulo: "Tu correo tiene un superpoder",
    partes: [
      { t: "valentina", k: "tu correo" },
      { t: "+roblox", k: "el alias (lo que quieras)" },
      { t: "@gmail.com", k: "igual que siempre" },
    ],
    bajada: "Todo llega a tu MISMO correo 📬",
    nota: [
      "Gmail ignora lo que va después del signo +. Si tu correo es valentina@gmail.com, un mensaje a valentina+roblox@gmail.com te llega igual.",
      "El truco: al registrarte en cada app o juego, usas un alias distinto. valentina+roblox, valentina+tiktok, valentina+tienda.",
      "¿Para qué? Para saber QUIÉN te escribe de verdad, y detectar mentiras. Lo vemos en la siguiente slide.",
      "Revelar las tres partes con clic.",
    ],
    preguntar: ["¿Qué alias usarías para tu juego favorito?"],
  },
  {
    id: "bandeja",
    bloque: 2,
    tema: "amarillo",
    min: 37,
    tipo: "bandeja",
    titulo: "¿A qué alias llegó?",
    correos: [
      { de: "Roblox", asunto: "Tu código de verificación", para: "+roblox", veredicto: "✅ Coincide: es real", tono: "ok" },
      { de: "Instagram", asunto: "🚨 Tu cuenta será bloqueada en 10 min", para: "+roblox", veredicto: "🚨 ¡Trampa! Instagram no conoce ese alias", tono: "mal" },
      { de: "TikTok", asunto: "🎁 Ganaste 1.000 monedas", para: "+tiktok", veredicto: "🟡 Coincide, pero premio + prisa: verifica en la app", tono: "ojo" },
      { de: "SuperOfertas", asunto: "Promos solo para ti", para: "+tiktok", veredicto: "🕵️ Filtración: alguien compartió tu correo", tono: "info" },
    ],
    nota: [
      "Puente con la sesión de phishing: el alias es una herramienta MÁS para detectarlo.",
      "Juego: para cada correo, ¿es real o trampa? Mirar SIEMPRE el «para». Clic revela el veredicto de cada fila.",
      "Correo 2: dice ser de Instagram pero llegó al alias de Roblox. Instagram nunca tuvo ese correo, así que es phishing seguro.",
      "Correo 3: el alias coincide, pero premio y prisa siguen siendo señales. Nunca entres por el enlace: abre la app directamente.",
      "Correo 4: una tienda que nunca conociste escribe al alias de TikTok. Ese correo se filtró o se vendió. Ya sabes de dónde salió.",
    ],
    preguntar: ["¿Real o trampa? ☝️ real · ✌️ trampa"],
    respuesta: "Real · Trampa · Verifica en la app · Filtración",
  },
  {
    id: "lupa-fotos",
    bloque: 2,
    tema: "violeta",
    min: 40,
    tipo: "tarjetas",
    titulo: "¿Esa foto es de verdad suya?",
    revelar: true,
    items: [
      { e: "👆", k: "1. Mantén presionada la foto", v: "o hazle captura" },
      { e: "🔍", k: "2. «Buscar con Google Lens»", v: "Google busca dónde más aparece" },
      { e: "🚨", k: "3. ¿Sale con otro nombre?", v: "perfil falso: no le escribas más" },
      { e: "🪞", k: "Bonus: busca TUS fotos", v: "y mira si alguien las está usando" },
    ],
    nota: [
      "Un perfil falso casi siempre usa fotos robadas. Hoy: cómo comprobarlo en 10 segundos.",
      "Cómo se hace: en Android, mantener presionada la foto en Chrome o en la app de Google → «Buscar con Google Lens». En iPhone: abrir la app de Google → ícono de la cámara (Lens) → escoger la captura de la foto de perfil. También sirve images.google.com desde un computador.",
      "Qué buscar: si la misma foto aparece en otra cuenta con otro nombre, en una página de modelos o en un banco de fotos, ese perfil robó la foto. La «niña de 13 años» que te escribe puede ser cualquiera.",
      "Bonus: buscar sus propias fotos de perfil sirve para descubrir cuentas que las suplantan (conecta con el caso de @vale.dibuja_ del bloque 1).",
      "Si NO aparece nada, no significa que sea real: solo que esa foto no está publicada en otro lado. La duda sigue: nunca sola, siempre con tu adulto.",
    ],
    preguntar: ["¿A quién le harían esta prueba?"],
  },
  {
    id: "roblox-escudo",
    bloque: 2,
    tema: "turquesa",
    min: 42,
    tipo: "app",
    titulo: "Tu juego en modo escudo",
    app: "Roblox (y parecidos)",
    pasos: [
      { e: "💬", k: "Chat solo con amigos", v: "o apagado" },
      { e: "🎙️", k: "Chat de voz apagado", v: "" },
      { e: "👥", k: "Quién te invita", v: "solo amigos" },
      { e: "📩", k: "Mensajes privados", v: "nadie o amigos" },
      { e: "🔐", k: "Verificación en 2 pasos", v: "contra robos" },
      { e: "🔢", k: "Controles parentales", v: "con tu adulto" },
    ],
    nota: [
      "Cada clic enciende un interruptor.",
      "Roblox: Configuración → Privacidad (quién puede chatear, invitarme, unirse a mí) y Seguridad → Verificación en dos pasos. Los controles parentales se manejan desde la cuenta del papá o la mamá vinculada.",
      "Free Fire y Fortnite tienen opciones parecidas (chat de voz, solicitudes de amistad, controles parentales de Epic). Minecraft: jugar en servidores de amigos o en realms privados.",
      "Los menús cambian seguido: revisarlos antes del taller.",
    ],
  },
  {
    id: "reglas-juego",
    bloque: 2,
    tema: "amarillo",
    min: 45,
    tipo: "tarjetas",
    titulo: "Las 4 reglas del juego",
    revelar: true,
    items: [
      { e: "🎁", k: "Regalo = trampa", v: "robux, diamantes y pases gratis crean deuda" },
      { e: "🚪", k: "El chat se queda en el juego", v: "no pasar a WhatsApp ni Discord" },
      { e: "🙊", k: "Tu info no juega", v: "nombre real, colegio y fotos, fuera" },
      { e: "🛒", k: "Solo la tienda oficial", v: "nunca compres cuentas ni skins afuera" },
    ],
    nota: [
      "Regalo = trampa: quien te regala algo después pide algo a cambio. «Te regalé robux, ahora me debes una foto».",
      "Pasar a WhatsApp o Discord saca la conversación de donde el juego puede moderarla. Es la señal más típica.",
      "Comprar cuentas, skins o monedas fuera de la tienda oficial es la estafa más común: pagas y no te llega nada, o te roban la cuenta.",
    ],
    preguntar: ["¿Alguna vez alguien les ha ofrecido regalos en un juego?"],
  },
  {
    id: "contrasena",
    bloque: 2,
    tema: "violeta",
    min: 47,
    tipo: "contrasena",
    titulo: "Reto: contraseña superpoderosa",
    // `regla` la verifica app.js en vivo: el consejo se pone en verde al cumplirse
    consejos: [
      { t: "Una frase loca con mayúsculas", regla: "frase" },
      { t: "Números y símbolos", regla: "simbolos" },
      { t: "Más de 12 letras", regla: "largo" },
      { t: "Nada de años ni claves famosas", regla: "personal" },
    ],
    lumi: { pose: "alerta", t: "¡Nunca escribas aquí tu clave real!" },
    nota: [
      "Juego en vivo: ellas dictan contraseñas inventadas y se escriben en el recuadro. El medidor dice qué tan fuerte es y cuánto tardaría un computador en adivinarla.",
      "Se puede escribir desde la vista presentador: aparece igual en el proyector.",
      "Empezar con «sofia2013» (débil), luego «12345678», luego construir juntas una frase: «MiGato$ComeArepa3Veces».",
      "Conectar con la foto del bloque 1: el nombre de tu mascota o tu año de nacimiento no sirven como contraseña ni como respuesta de seguridad.",
      "Una contraseña distinta para cada app: si te roban una, no te roban todas.",
    ],
    preguntar: ["¡Díctenme una contraseña inventada!"],
  },
  {
    id: "pregunta-seguridad",
    bloque: 2,
    tema: "amarillo",
    min: 50,
    tipo: "pregunta",
    eyebrow: "Truco de guardiana",
    situacion: "La app te pregunta: «¿Cómo se llamaba tu primera mascota?»",
    titulo: "¿Qué respondes?",
    opciones: ["Lupe", "Lupe2013", "Una mentira que solo tú sabes: «ArepaVoladora»"],
    correcta: 2,
    explica: "Es otra contraseña: no tiene que ser verdad 🤫",
    nota: [
      "Conectar con la foto del bloque 1: «Lupe» salía en la publicación de @vale.dibuja. Cualquiera que vio la foto puede responder la pregunta y recuperar SU cuenta.",
      "El truco: responder con una mentira que no se puede adivinar y anotarla en casa con su adulto (en la misma libreta de los alias, o en el gestor de contraseñas del celular de la familia).",
      "Lo mismo vale para «¿en qué colegio estudiaste?», «¿nombre de tu mejor amiga?», «¿ciudad donde naciste?»: todo eso está en tus redes.",
      "Extra: el correo o celular de recuperación de la cuenta debería ser el de su adulto, no el de una amiga.",
    ],
    respuesta: "3 · Una mentira secreta. Lupe y Lupe2013 se adivinan viendo la foto.",
  },
  {
    id: "sesiones",
    bloque: 2,
    tema: "violeta",
    min: 52,
    tipo: "sesiones",
    titulo: "¿Quién más tiene abierto tu WhatsApp?",
    app: "Dispositivos vinculados",
    dispositivos: [
      { e: "💻", k: "Google Chrome (Windows)", v: "Activo hace 5 min", intruso: true },
      { e: "🖥️", k: "Computador de casa", v: "Hoy, 7:10 a. m." },
    ],
    rutas: [
      { k: "WhatsApp", v: "Ajustes → Dispositivos vinculados" },
      { k: "Instagram", v: "Centro de cuentas → Contraseña y seguridad → Dónde iniciaste sesión" },
      { k: "Google", v: "Tu cuenta → Seguridad → Tus dispositivos" },
    ],
    nota: [
      "Situación para contar: «Una amiga del salón sabe cosas de tus chats que tú no le contaste». Muchas veces es que alguien abrió tu WhatsApp Web en un computador (del colegio, de un café internet, de una amiga) y nunca lo cerraste. Desde ahí lee TODO en vivo, y tú no ves ninguna alerta.",
      "Clic 1: aparece el intruso. Clic 2: se cierra esa sesión. Luego se revelan las rutas.",
      "WhatsApp: Ajustes → Dispositivos vinculados. Tocar el dispositivo que no reconoces → Cerrar sesión.",
      "Instagram: Configuración y privacidad → Centro de cuentas → Contraseña y seguridad → Dónde iniciaste sesión. Ahí se puede cerrar la sesión de cada celular o computador. Google: myaccount.google.com → Seguridad → Tus dispositivos.",
      "Después de cerrar una sesión extraña: cambiar la contraseña y activar la verificación en 2 pasos (WhatsApp: Ajustes → Cuenta → Verificación en dos pasos).",
      "Hábito: revisarlo una vez al mes con su adulto, y SIEMPRE cerrar sesión cuando usen un computador que no es suyo.",
      "⚠️ Verificar nombres de menús en un celular real la semana del taller.",
    ],
    preguntar: ["¿Alguna vez abrieron su WhatsApp o Instagram en un computador que no es suyo?"],
  },
  {
    id: "lineas",
    bloque: 2,
    tema: "turquesa",
    min: 55,
    tipo: "lineas",
    titulo: "Siempre hay ayuda",
    lineas: [
      { n: "141", k: "ICBF", v: "Gratis · 24 horas" },
      { n: "123", k: "Emergencias", v: "Policía · peligro ya" },
      { n: "155", k: "Línea Mujer", v: "Orientación · 24 horas" },
      { n: "🌐", k: "teprotejo.org", v: "Reporta contenido" },
      { n: "🚓", k: "CAI Virtual", v: "caivirtual.policia\u200b.gov.co" },
    ],
    nota: [
      "Leer cada línea rápido y decir para qué sirve. Están en la guía que se llevan.",
      "Aclarar para qué sirve cada una con un ejemplo de hoy: una oferta sospechosa de encuentro o alguien siguiéndote → 123. Una cuenta que se hace pasar por ti con amenazas → CAI Virtual. Contenido de niñas en redes → Te Protejo.",
      "Si el taller es en Bogotá, mencionar la Línea 106 (orientación para niñas, niños y adolescentes).",
    ],
  },
  {
    id: "cierre",
    bloque: 2,
    tema: "rosa",
    min: 57,
    tipo: "cierre",
    titulo: "¡Ya eres Guardiana Digital!",
    chips: [
      { e: "📸", t: "Publico después" },
      { e: "🙅‍♀️", t: "Nunca sola" },
      { e: "📧", t: "Uso alias" },
      { e: "🎮", t: "Juego segura" },
    ],
    nota: [
      "Las cuatro ideas de hoy, en voz alta, todas de pie.",
      "Agradecer. Foto grupal (sin publicar caras de niñas sin autorización de sus acudientes).",
      "Cerrar con la frase: «internet es una ciudad increíble, y ahora tienen las llaves para moverse en ella».",
    ],
  },
];
