/* Contenido — Phishing · She Is Foundation · SESIÓN 2 (1 hora).
 *
 * Motor en ../../_base. De este archivo salen las slides, la vista presentador,
 * el guion (node ../../_base/herramientas/guion.mjs) y la guía.
 *
 * Base: el Canva de la cohorte 1 (fuente/phishing-cohorte-1-canva.pdf). Se
 * conservan su estructura y sus reglas (qué es, tipos, anatomía de un correo,
 * dominios, banderas rojas, protocolo NO CLIC · RESPIRA · VERIFICA, casos,
 * buenas prácticas) para que las dos cohortes aprendan lo mismo, pero con
 * ejemplos de ELLAS: Roblox, Free Fire, TikTok, Instagram y WhatsApp en lugar
 * de bancos, directivos y EPS.
 *
 * El grupo participa poco: votos con los dedos o levantando la mano, más
 * slides y menos conversación. Si nadie responde en 5 segundos, revelar.
 */

globalThis.META = {
  titulo: "Phishing",
  subtitulo: "Sesión 2 · El anzuelo en tu celular — She Is Foundation",
  organiza: "She Is",
  apoya: "Sapientiam · ETITC",
  presupuesto: 60,
  bloques: {
    1: "Bloque 1 · ¿Qué es el phishing?",
    2: "Bloque 2 · Detecta el anzuelo",
    3: "Bloque 3 · Qué hago",
  },
  contacto: { nombre: "She Is Foundation", whatsapp: "+57 310 785 9540", correo: "info@she-is.org" },
  logos: [
    { src: "../img/she-is.png", nombre: "She Is Foundation", alto: 13 },
    { src: "../../_base/img/sapientiam.png", nombre: "Semillero<br>Sapientiam", oscuro: true },
    { src: "../../_base/img/etitc.png", nombre: "Escuela Tecnológica Instituto Técnico Central", alto: 9 },
  ],
  contexto: [
    "**Es la sesión 2 de She Is.** Mismo tema que la cohorte 1 (Canva en `fuente/`), con ejemplos de su edad. La sesión 3 (Escudo Digital) arranca con un repaso de esta: la regla PARA · PIENSA · VERIFICA tiene que quedar clara.",
    "**La sesión 1 fue «Tu identidad es única»** (datos que no se publican, perfiles falsos, piensa antes de compartir). Puente para «A tu medida»: lo que publican es lo que usa el mensaje trampa para parecer real.",
    "**1 hora, sin pausa.** El grupo participa poco: preguntar, esperar 5 segundos y, si nadie responde, revelar y seguir.",
    "Sin dispositivos: toda la práctica es con maquetas en pantalla. Lo que hay que configurar va en la guía PDF.",
  ],
  quienOrganiza: "She Is Foundation",
  materiales: [
    "Computador + proyector (o TV) + extensión de pantalla, no espejo.",
    "Mandar la guía PDF a las familias después del taller.",
  ],
};

globalThis.SLIDES = [
  /* ═══════════════════════ BLOQUE 1 ═══════════════════════ */
  {
    id: "portada",
    bloque: 1,
    tema: "turquesa",
    min: 0,
    tipo: "portada",
    titulo: "Phishing",
    bajada: "El anzuelo en tu celular 🎣",
    nota: [
      "Mientras entran: esta slide en pantalla.",
      "Bienvenida: «hoy vamos a aprender a reconocer el truco más usado para robar cuentas: el phishing. Se lee “fishing”, como pescar: te lanzan un anzuelo y esperan que muerdas».",
    ],
  },
  {
    id: "lumi",
    bloque: 1,
    tema: "amarillo",
    min: 1,
    tipo: "mensaje",
    lumiGrande: "hola",
    titulo: "¡Hola! Soy Lumi",
    bajada: "Hoy votamos con los dedos",
    chips: [
      { e: "☝️", t: "1 dedo" },
      { e: "✌️", t: "2 dedos" },
      { e: "🤟", t: "3 dedos" },
    ],
    nota: [
      "Lumi ya la conocen de la sesión 1 (Tu identidad es única): saludarla como a una vieja amiga.",
      "Cómo votamos: cuando haya opciones 1, 2 o 3, levantan esa cantidad de dedos. Nadie tiene que hablar si no quiere: con los dedos basta.",
    ],
  },
  {
    id: "acuerdos",
    bloque: 1,
    tema: "rosa",
    min: 3,
    tipo: "tarjetas",
    titulo: "Nuestros acuerdos",
    items: [
      { e: "🤫", k: "Lo que se dice aquí", v: "se queda aquí" },
      { e: "🙊", k: "Sin nombres reales", v: "decimos «una amiga»" },
      { e: "💜", k: "No hay preguntas tontas", v: "todas valen" },
      { e: "✋", k: "Puedo pasar", v: "si no quiero hablar" },
    ],
    nota: [
      "Leer cada acuerdo y pedir un pulgar arriba.",
      "PROTOCOLO: si una niña cuenta algo que suena a riesgo real (acoso fuerte, alguien que le ofrece dinero o encuentros, amenazas), NO profundizar frente al grupo. Agradecer, decir «hablemos al final» y hacerlo en privado. Luego informar a quien organiza para activar la ruta (orientación del colegio, Línea 141 ICBF, 123 si hay peligro inmediato).",
    ],
  },
  {
    id: "que-es",
    bloque: 1,
    tema: "violeta",
    min: 4,
    tipo: "mensaje",
    emoji: "🎣",
    titulo: "¿Qué es el phishing?",
    bajada: "Alguien se disfraza de quien confías para robarte",
    chips: [
      { e: "🎭", t: "Se disfraza" },
      { e: "😱", t: "Te asusta o te emociona" },
      { e: "🔑", t: "Quiere tu clave, tu código o tu dinero" },
    ],
    revelar: true,
    nota: [
      "Definición de la cohorte 1: «técnica de suplantación de identidad digital para robar información; aprovecha emociones como el miedo y la urgencia».",
      "En palabras de ellas: alguien se hace pasar por Roblox, por TikTok, por tu amiga o por tu mamá, y te pone nerviosa o emocionada para que actúes sin pensar.",
      "Revelar los tres chips uno por uno.",
    ],
  },
  {
    id: "encuesta",
    bloque: 1,
    tema: "coral",
    min: 6,
    tipo: "encuesta",
    titulo: "¿Te ha llegado un mensaje raro por…?",
    opciones: [
      { e: "💬", t: "WhatsApp" },
      { e: "🎮", t: "Un juego" },
      { e: "📧", t: "Correo o SMS" },
    ],
    nota: [
      "Leer cada opción y que levanten la mano. No hay que contar nada, solo levantar la mano.",
      "Si levantan muchas manos: «¿ven? Le pasa a casi todo el mundo. Por eso vale la pena aprender a reconocerlo».",
    ],
    preguntar: ["Levanten la mano: ¿a quién le ha llegado por WhatsApp? ¿Por un juego? ¿Por correo?"],
  },
  {
    id: "disfraces",
    bloque: 1,
    tema: "turquesa",
    min: 8,
    tipo: "tarjetas",
    titulo: "Los disfraces del phishing",
    revelar: true,
    items: [
      { e: "📧", k: "A miles a la vez", v: "«¡Ganaste un premio!» a todo el mundo" },
      { e: "🎯", k: "A tu medida", v: "sabe tu nombre, tu juego, tu colegio" },
      { e: "💬", k: "Por WhatsApp o SMS", v: "«Hola, soy yo con número nuevo»" },
      { e: "📞", k: "Por llamada", v: "«Soy de soporte, dame el código»" },
    ],
    nota: [
      "Son los tipos de la cohorte 1 con nombre de niña: phishing masivo, spear phishing, smishing y vishing. Los nombres técnicos no hace falta memorizarlos.",
      "«A tu medida» conecta con lo que publican: si tu perfil dice tu colegio y tu juego favorito, el mensaje trampa puede usarlo para parecer real.",
      "Llamadas: en Colombia se han reportado llamadas de supuesto «soporte de WhatsApp» que piden el código o hacen agregar un número (Infobae, 12-04-2026).",
    ],
  },
  {
    id: "dato-roblox",
    bloque: 1,
    tema: "noche",
    min: 11,
    tipo: "dato",
    cifra: "610.000",
    titulo: "cuentas de Roblox robadas",
    bajada: "entre octubre de 2025 y enero de 2026, por un solo grupo",
    detalle: "Las robaron con «trucos» falsos para el juego que en realidad eran programas espía.",
    fuente: "Malwarebytes (30-04-2026), sobre la captura de los responsables en Ucrania",
    nota: [
      "Leer la cifra y dejar un silencio.",
      "Contexto para quien facilita: tres personas capturadas en Lviv (Ucrania). Distribuían programas disfrazados de mejoras para el juego, que robaban las claves guardadas en el computador; vendían las cuentas (357 eran «élite», muy valiosas). Ganaron unos 225.000 dólares.",
      "Otro dato por si preguntan: Kaspersky detectó 1,6 millones de ataques disfrazados de archivos de Roblox solo en 2024 (comunicado del 19-02-2025).",
      "Mensaje: «no es que ustedes sean descuidadas: es que hay gente que se dedica a esto. Por eso necesitamos trucos para reconocerlo».",
    ],
  },

  /* ═══════════════════════ BLOQUE 2 ═══════════════════════ */
  {
    id: "caso-amiga",
    bloque: 2,
    tema: "noche",
    min: 13,
    tipo: "chat",
    titulo: "Caso: tu amiga con número nuevo",
    bajada: "Encuentra las 🚩",
    contacto: { nombre: "+57 321 •••• 118", e: "👧🏻" },
    mensajes: [
      { t: "Holiii soy Vale 😊 cambié de número, guárdame", pista: "Número desconocido" },
      { t: "Oye, por error me llegó un código a tu cel 🙈", pista: "Habla de un código" },
      { t: "¿Me lo pasas? Son 6 números", pista: "Te pide el código" },
      { t: "Porfa rápido que se vence 😭", pista: "Prisa" },
      { t: "No le digas a nadie que perdí el cel 🤫", pista: "Secreto" },
    ],
    nota: [
      "CASO FICTICIO basado en la estafa más común para robar WhatsApp: con ese código de 6 números, el ladrón abre TU WhatsApp en su celular y te deja por fuera. Después le escribe a todos tus contactos pidiendo más códigos o dinero.",
      "Leer el chat completo. Por cada alarma que identifiquen, clic y aparece la bandera.",
      "La clave: ese código es la llave de tu cuenta. NADIE que de verdad sea tu amiga lo necesita.",
    ],
    preguntar: ["¿Qué te parece más raro de este chat?"],
    respuesta: "Número nuevo + pide el código + prisa + secreto. Cualquiera de esas ya es para desconfiar.",
  },
  {
    id: "caso-amiga-que-hago",
    bloque: 2,
    tema: "violeta",
    min: 17,
    tipo: "escenario",
    eyebrow: "¿Qué harías tú?",
    titulo: "«Vale» insiste",
    situacion: "El número nuevo te sigue escribiendo: «¿me lo pasas o no? 😡»",
    opciones: [
      { t: "Le mando el código, es mi amiga", pasa: "Te roban el WhatsApp y le escriben a todos tus contactos 😟" },
      { t: "Le pregunto por el chat si de verdad es ella", pasa: "El ladrón responde «sí, soy yo, ¡apúrate!» 🤷" },
      { t: "La llamo a su número de siempre o le pregunto en persona", pasa: "Vale no sabía nada: era un ladrón 💪", ok: true },
    ],
    nota: [
      "Revelar las consecuencias una por una.",
      "La opción 2 es la trampa más sutil: preguntarle al MISMO número no sirve, porque responde el ladrón. Se verifica por OTRO camino: el número de siempre, en persona, o preguntándole a alguien que la conozca.",
    ],
    respuesta: "3 · Verificar por otro camino.",
  },
  {
    id: "regla-codigo",
    bloque: 2,
    tema: "amarillo",
    min: 20,
    tipo: "regla",
    titulo: "Tu código es SECRETO",
    pasos: [
      { e: "🔢", k: "NUNCA LO COMPARTAS", v: "ni con tu mejor amiga" },
      { e: "🏢", k: "NINGUNA APP", v: "te lo pide: ni WhatsApp, ni Roblox, ni TikTok" },
      { e: "📞", k: "VERIFICA", v: "por otro camino" },
      { e: "🔐", k: "2 PASOS", v: "actívalos: aunque roben el código, no entran" },
    ],
    nota: [
      "Revelar una por una. Es la regla más importante de hoy: que la repitan en voz alta.",
      "2 pasos en WhatsApp: Ajustes → Cuenta → Verificación en dos pasos → un PIN de 6 números que solo tú sabes. Queda en la guía para hacerlo en casa con su adulto.",
    ],
    preguntar: ["Todas juntas: ¿mi código se comparte? (no)"],
  },
  {
    id: "anatomia",
    bloque: 2,
    tema: "coral",
    min: 22,
    tipo: "tarjetas",
    titulo: "Anatomía de un mensaje trampa",
    revelar: true,
    items: [
      { e: "👤", k: "Remitente falso", v: "«Roblox Soporte» desde soporte@r0blox-premios.net" },
      { e: "🚨", k: "Asunto alarmante", v: "«Tu cuenta será eliminada»" },
      { e: "⏰", k: "Urgencia", v: "«Tienes 24 horas o la pierdes»" },
      { e: "🔗", k: "Enlace engañoso", v: "dice roblox.com, pero lleva a otro lado" },
    ],
    nota: [
      "Es la «anatomía de un correo» de la cohorte 1, con Roblox en vez del banco (antes: soporte@bancolombia-seguro.net).",
      "Otras banderas rojas de la cohorte 1 para mencionar: saludo genérico («Estimado usuario» en vez de tu nombre), errores de ortografía y pedir cosas raras (tu clave, un código, una foto, dinero).",
    ],
  },
  {
    id: "real-o-trampa",
    bloque: 2,
    tema: "coral",
    min: 25,
    tipo: "semaforo",
    titulo: "¿Real o trampa?",
    items: [
      { t: "Tu profe comparte en el grupo del salón el link de la tarea", color: "verde" },
      { t: "TikTok: «alguien inició sesión en un dispositivo nuevo»", color: "amarillo" },
      { t: "Roblox: «ganaste 10.000 Robux, entra aquí con tu usuario y clave»", color: "rojo" },
      { t: "Una amiga te manda «😱 mira quién sale en esta foto» con un link", color: "rojo" },
      { t: "Free Fire: «diamantes gratis si pones tu cuenta»", color: "rojo" },
      { t: "Instagram: «tu cuenta infringe derechos de autor, apela aquí o se borra»", color: "rojo" },
    ],
    nota: [
      "Leer cada situación, que digan el color con los dedos (☝️ verde · ✌️ amarillo · 🤟 rojo) y clic para revelar.",
      "El de TikTok es amarillo: esos avisos existen de verdad, pero NO se entra por el enlace. Se abre la app y se revisa ahí (Configuración → Seguridad).",
      "«Mira quién sale en esta foto» es clásico: la cuenta de tu amiga ya fue robada y el link roba la tuya. Si tu amiga te manda algo raro, pregúntale por otro camino.",
      "Instagram «derechos de autor» es una de las trampas más usadas contra cuentas con seguidores.",
    ],
    respuesta: "🟢 · 🟡 · 🔴 · 🔴 · 🔴 · 🔴",
  },
  {
    id: "enlace-detective",
    bloque: 2,
    tema: "coral",
    min: 29,
    tipo: "pregunta",
    eyebrow: "Detective de enlaces",
    situacion: "«🎁 Roblox: reclama tus 1.000 robux gratis aquí 👉»",
    titulo: "¿Cuál enlace es de verdad Roblox?",
    opciones: ["roblox.com.robux-gratis.co/premio", "rob1ox.com/robux", "www.roblox.com/robux"],
    correcta: 2,
    explica: "El dueño del enlace es lo que va justo antes de la primera «/». Léelo de atrás hacia adelante.",
    nota: [
      "Escribir o señalar los tres enlaces despacio. Votan con los dedos y se revela.",
      "1 · roblox.com.robux-gratis.co: empieza con «roblox.com», pero lo que manda es el FINAL antes de la primera barra: «robux-gratis.co». El dueño es otra persona. Es la trampa más usada.",
      "2 · rob1ox.com: cambiaron la l por un 1. Otras letras gemelas: 0 y o, rn y m, I mayúscula y l.",
      "3 · www.roblox.com/robux: antes de la primera barra dice roblox.com. Es el real. Aun así, «robux gratis» sigue siendo señal de trampa: el enlace real no vuelve real la oferta.",
      "Truco para quien facilita: en la barra se lee de derecha a izquierda desde la primera «/»: .com → roblox. Lo que va a la izquierda de eso (www., premios., etc.) lo pone el mismo dueño.",
    ],
    preguntar: ["¿Cuál es el de verdad? ☝️ ✌️ 🤟"],
    respuesta: "3 · www.roblox.com. El 1 es de «robux-gratis.co» y el 2 cambió la l por un 1.",
  },
  {
    id: "enlace-instagram",
    bloque: 2,
    tema: "violeta",
    min: 32,
    tipo: "pregunta",
    eyebrow: "Detective de enlaces · 2",
    situacion: "«Instagram: verifica tu cuenta o se desactiva hoy 👉»",
    titulo: "¿Cuál es de verdad Instagram?",
    opciones: ["instagram.com.soporte-cuentas.co/verificar", "instagrarn.com/login", "instagram.com/login"],
    correcta: 2,
    explica: "Ojo con las letras gemelas: «rn» parece una «m».",
    nota: [
      "Mismo ejercicio, ahora solitas: votan y se revela.",
      "1 · el dueño es «soporte-cuentas.co» (lo que va antes de la primera /).",
      "2 · «instagrarn» con r-n: de lejos parece una m. Es la trampa de la cohorte 1 con banc0 (cero en vez de o).",
    ],
    respuesta: "3 · instagram.com/login (el dueño es instagram.com).",
  },
  {
    id: "trucos-correo",
    bloque: 2,
    tema: "turquesa",
    min: 34,
    tipo: "tarjetas",
    titulo: "Más trucos contra correos trampa",
    revelar: true,
    items: [
      { e: "👆", k: "Mantén presionado", v: "ves a dónde va el enlace sin abrirlo" },
      { e: "🔎", k: "Busca al dueño", v: "lo que va antes de la primera «/»" },
      { e: "📱", k: "Abre la app, no el enlace", v: "si es real, allá también aparece" },
      { e: "📬", k: "Pregúntale a Instagram", v: "«Correos recientes» muestra los que sí son suyos" },
    ],
    nota: [
      "1 · MANTENER PRESIONADO: en el celular, dejar el dedo sobre el enlace (sin soltar rápido) muestra la dirección completa sin abrirla. En computador basta con pasar el mouse por encima y mirar la esquina de abajo.",
      "2 · EL DUEÑO: lo que acaban de practicar en los dos quiz.",
      "3 · ABRIR LA APP: si el correo dice «tu cuenta será bloqueada» o «ganaste un premio», cerrar el correo y abrir la app o el juego directamente. Si es verdad, el aviso también está ahí adentro.",
      "4 · CORREOS RECIENTES (Instagram): Configuración y privacidad → Centro de cuentas → Contraseña y seguridad → Correos recientes. Ahí aparecen los correos que Instagram de verdad te mandó en los últimos días (de seguridad y de inicio de sesión). Si el correo que te asustó no está en esa lista, no es de Instagram. ⚠️ Verificar la ruta en un celular real la semana del taller: Meta la mueve seguido.",
      "En la próxima sesión viene otro truco de correo: los alias. Solo anunciarlo.",
    ],
    preguntar: ["¿Cuál de estos van a probar primero?"],
  },

  /* ═══════════════════════ BLOQUE 3 ═══════════════════════ */
  {
    id: "protocolo",
    bloque: 3,
    tema: "amarillo",
    min: 37,
    tipo: "regla",
    titulo: "Si algo huele a trampa",
    pasos: [
      { e: "✋", k: "NO HAGAS CLIC", v: "ni descargues nada" },
      { e: "😮‍💨", k: "RESPIRA", v: "la urgencia ES la trampa" },
      { e: "🔎", k: "VERIFICA", v: "por otro camino: la app, el número de siempre" },
      { e: "🗣️", k: "CUÉNTALE", v: "a tu adulto de confianza" },
    ],
    nota: [
      "Es el protocolo de la cohorte 1 (no hagas clic · respira · verifica) con un cuarto paso para ellas: contarle a un adulto.",
      "En corto, para que lo recuerden: PARA · PIENSA · VERIFICA. La próxima sesión arranca preguntándoles esto.",
    ],
    preguntar: ["¿Cuál es el paso que más les cuesta?"],
  },
  {
    id: "ya-cai",
    bloque: 3,
    tema: "rosa",
    min: 39,
    tipo: "escenario",
    eyebrow: "¿Qué harías tú?",
    titulo: "Ya hiciste clic y pusiste tu clave 😱",
    situacion: "Entraste al link de «Robux gratis» y escribiste tu usuario y contraseña.",
    opciones: [
      { t: "No digo nada, me da miedo que me regañen", pasa: "El ladrón tiene tiempo para usar tu cuenta 😟" },
      { t: "Borro el mensaje y ya", pasa: "La clave robada sigue funcionando 🔓" },
      { t: "Cambio la clave ya, cierro sesiones, activo 2 pasos y le cuento a mi adulto", pasa: "Cortas al ladrón a tiempo 💪", ok: true },
    ],
    nota: [
      "Mensaje clave: caer le pasa a cualquiera. Lo que importa es actuar RÁPIDO y contarlo. Nadie debería regañarte por avisar.",
      "Rescate: 1) cambiar la contraseña desde la app oficial, 2) cerrar las sesiones abiertas (Configuración → Seguridad), 3) activar 2 pasos, 4) si usaste esa clave en otras apps, cambiarla allá también, 5) avisar a tus amigos si el ladrón alcanzó a escribirles.",
      "Si ya no puedes entrar: «¿Olvidaste tu contraseña?» y soporte oficial. Nunca le pagues a quien diga que te la recupera.",
    ],
    respuesta: "3 · Cambiar clave, cerrar sesiones, 2 pasos y contarle a un adulto.",
  },
  {
    id: "anzuelos-juego",
    bloque: 3,
    tema: "noche",
    min: 42,
    tipo: "tarjetas",
    titulo: "Los anzuelos de los juegos",
    revelar: true,
    items: [
      { e: "💎", k: "Generadores de Robux o diamantes", v: "no existen: son trampa" },
      { e: "🧩", k: "Trucos y «mods»", v: "así robaron las 610.000 cuentas" },
      { e: "🎁", k: "«Te regalo un skin»", v: "a cambio de tu usuario y clave" },
      { e: "🛒", k: "Comprar fuera de la tienda", v: "pagas y no llega nada" },
    ],
    nota: [
      "Son los «casos reales» de la cohorte 1, pero en su mundo. Kaspersky dice que el disfraz favorito de los ataques a jugadores son justamente los trucos, mods y generadores de moneda gratis.",
      "Regla: si es gratis y parece demasiado bueno, el precio eres tú (tu cuenta).",
    ],
  },
  {
    id: "voz-falsa",
    bloque: 3,
    tema: "violeta",
    min: 45,
    tipo: "mensaje",
    emoji: "🤖",
    titulo: "Ahora hasta la voz puede ser falsa",
    bajada: "Con inteligencia artificial copian voces y caras",
    chips: [
      { e: "🎙️", t: "Un audio de «tu mamá»" },
      { e: "📹", t: "Un video de «tu amiga»" },
      { e: "🔑", t: "Pregunta la palabra clave" },
    ],
    revelar: true,
    nota: [
      "Es la parte de deepfakes de la cohorte 1, en su versión: ya no solo imitan correos, también voces y videos. Un audio que suena igual a tu mamá pidiéndote algo urgente puede ser falso.",
      "Defensa: una palabra clave que solo sabe tu familia (se profundiza en la próxima sesión) y llamar al número de siempre.",
      "Dato de la cohorte 1 para quien facilita: en Colombia, la Ley 2502 de 2025 castiga más fuerte la suplantación con deepfakes.",
    ],
  },
  {
    id: "escudo-antiphishing",
    bloque: 3,
    tema: "turquesa",
    min: 47,
    tipo: "tarjetas",
    titulo: "Tu escudo anti-phishing",
    revelar: true,
    items: [
      { e: "🔐", k: "2 pasos", v: "en WhatsApp, Instagram, TikTok y tu juego" },
      { e: "🔑", k: "Una clave por app", v: "si roban una, no roban todas" },
      { e: "📲", k: "Todo actualizado", v: "el celular y las apps" },
      { e: "📎", k: "Archivos que no pediste", v: "no se abren, aunque sean de conocidos" },
      { e: "🏪", k: "Solo la tienda oficial", v: "para apps, juegos y trucos" },
    ],
    nota: [
      "Son las buenas prácticas de la cohorte 1 en su lenguaje. Las rutas para activar los 2 pasos van en la guía PDF.",
      "Si solo recuerdan una: activar los 2 pasos en WhatsApp esta semana.",
    ],
  },
  {
    id: "quiz-final",
    bloque: 3,
    tema: "coral",
    min: 50,
    tipo: "pregunta",
    eyebrow: "Quiz final",
    situacion: "Te llaman: «Soy de soporte de WhatsApp. Detectamos algo raro. Dame el código de 6 números que te acaba de llegar».",
    titulo: "¿Qué haces?",
    opciones: ["Se lo doy, es soporte", "Le pido que me demuestre que es de WhatsApp", "Cuelgo: WhatsApp nunca pide el código"],
    correcta: 2,
    explica: "Ninguna app te pide el código. Nunca.",
    nota: [
      "Caso real: en Colombia se han reportado llamadas de supuesto soporte de WhatsApp para robar cuentas (Infobae, 12-04-2026).",
      "La opción 2 también es trampa: un estafador siempre tiene cómo «demostrarlo». No se negocia: se cuelga.",
    ],
    respuesta: "3 · Colgar.",
  },
  {
    id: "lineas",
    bloque: 3,
    tema: "turquesa",
    min: 53,
    tipo: "lineas",
    titulo: "Siempre hay ayuda",
    lineas: [
      { n: "141", k: "ICBF", v: "Gratis · 24 horas" },
      { n: "123", k: "Emergencias", v: "Policía · peligro ya" },
      { n: "155", k: "Línea Mujer", v: "Orientación · 24 horas" },
      { n: "🌐", k: "teprotejo.org", v: "Reporta contenido" },
      { n: "🚓", k: "CAI Virtual", v: "caivirtual.policia\u200b.gov.co" },
    ],
    nota: [
      "Leer rápido. Para phishing lo más útil: CAI Virtual (denunciar si te robaron una cuenta o dinero) y reportar el mensaje dentro de la app.",
      "Aclarar para qué sirve cada una con un ejemplo de hoy: una oferta sospechosa de encuentro o alguien siguiéndote → 123. Una cuenta que se hace pasar por ti con amenazas → CAI Virtual. Contenido de niñas en redes → Te Protejo.",
      "Si el taller es en Bogotá, mencionar la Línea 106 (orientación para niñas, niños y adolescentes).",
    ],
  },
  {
    id: "cierre",
    bloque: 3,
    tema: "rosa",
    min: 56,
    tipo: "cierre",
    titulo: "¡No muerdo el anzuelo!",
    chips: [
      { e: "🔢", t: "Mi código es secreto" },
      { e: "🔎", t: "Busco al dueño del enlace" },
      { e: "📞", t: "Verifico por otro camino" },
      { e: "🗣️", t: "Le cuento a mi adulto" },
    ],
    nota: [
      "Las cuatro ideas de hoy, en voz alta.",
      "Anunciar la próxima sesión: Escudo Digital, herramientas para protegerse (poderes secretos contra el acoso, trucos de correo, juegos seguros).",
      "Recordar que la guía PDF les llega a sus familias.",
    ],
  },
];
