/* Contenido del taller — fuente única.
 *
 * De este archivo salen TRES vistas del mismo objeto:
 *   - las slides que ven las niñas (index.html)
 *   - la vista presentador en la segunda pantalla (index.html?presentador)
 *   - el guion impreso (guion.md, generado con `node ../_base/herramientas/guion.mjs`)
 *
 * Cada slide tiene dos caras:
 *   lo visual   → titular corto, emoji grande, casi nada de texto
 *   `nota`      → lo que dice quien facilita; nunca se proyecta
 *   `preguntar` → preguntas para lanzar a la sala (salen resaltadas en el guion)
 *   `respuesta` → lo que se espera oír; solo lo ve quien facilita
 *
 * `min` es el minuto en que debería caer la slide con un presupuesto de 135
 * minutos (incluye la pausa). Si una slide se corre más de dos minutos de su
 * marca, se acorta la conversación, no el taller.
 *
 * SESIÓN 2. La sesión 1 (ver estructura.pdf) ya cubrió: perfiles falsos,
 * grooming y el amigo del juego, mensajes urgentes y robo de código, el grupo
 * del colegio, huella digital, sextorsión, «no es tu culpa», PARA·GUARDA·
 * BLOQUEA·CUENTA, red de confianza, 5 reglas y líneas de ayuda. Aquí NO se
 * repite: se da por sabido y se pasa de reconocer el peligro a protegerse.
 *
 * Votación sin materiales: las niñas levantan 1, 2 o 3 dedos.
 * Sin dispositivos: toda la práctica es con maquetas en pantalla.
 */

globalThis.META = {
  titulo: "Escudo Digital",
  subtitulo: "Sesión 2 · Herramientas de guardiana — taller para niñas de 10 a 15 años",
  organiza: "Fundasol 126",
  apoya: "Sapientiam · ETITC",
  presupuesto: 135,
  bloques: {
    1: "Bloque 1 · Lo que no se ve",
    2: "Bloque 2 · Trucos de guardiana",
  },
  // Para la guía (contacto por confirmar: hay dos fundaciones con ese nombre)
  contacto: { nombre: "Fundación FUNDASOL 126", whatsapp: "+57 312 405 8362", correo: "contacto@fundasol126.org" },
  logos: [
    { src: "img/fundasol.png", nombre: "Fundasol 126" },
    { src: "../_base/img/sapientiam.png", nombre: "Semillero<br>Sapientiam", oscuro: true },
    { src: "../_base/img/etitc.png", nombre: "Escuela Tecnológica Instituto Técnico Central", alto: 9 },
  ],
  // Para el guion: qué ya se dio, protocolo y materiales de ESTE taller
  contexto: [
    "**Es la sesión 2.** La sesión 1 (`estructura.pdf`) ya cubrió perfiles falsos, grooming, mensajes urgentes, el grupo del colegio, huella digital, sextorsión, «no es tu culpa», PARA·GUARDA·BLOQUEA·CUENTA, red de confianza y líneas de ayuda. Aquí se da por sabido: no volver a explicarlo, solo conectarlo.",
    "Sin dispositivos: toda la práctica es con maquetas en pantalla y se lleva a casa en «Mi plan de guardiana».",
  ],
  quienOrganiza: "Fundasol 126",
  materiales: [
    "Computador + proyector (o TV) + extensión de pantalla, no espejo.",
    "Papelitos y una caja o bolsa para el **buzón de preguntas anónimas**.",
    "Una hoja o tarjeta por niña para **Mi plan de guardiana** (4 campos: adulto de confianza, palabra clave, alias para juegos, qué voy a activar).",
    "Revisar antes los menús de Instagram (Restringir, Palabras ocultas, Limitar), TikTok, WhatsApp y Roblox: cambian con las actualizaciones.",
    "Parlantes: la pausa tiene música y una campana en el último minuto.",
  ],
};

globalThis.SLIDES = [
  /* ═══════════════════════ BLOQUE 1 ═══════════════════════ */
  {
    id: "portada",
    bloque: 1,
    tema: "violeta",
    min: 0,
    tipo: "portada",
    titulo: "Escudo Digital",
    bajada: "Segunda misión: de reconocer a protegerte",
    nota: [
      "Mientras entran: esta slide en pantalla.",
      "Bienvenida. Recordar que es la segunda sesión: «la vez pasada aprendimos a preguntarnos quién está detrás de la pantalla; hoy vamos a aprender a protegernos con herramientas de verdad».",
      "Dos partes: primero lo que no se ve (lo que revelamos sin darnos cuenta y las trampas nuevas), después trucos prácticos de guardiana.",
    ],
  },
  {
    id: "lumi",
    bloque: 1,
    tema: "amarillo",
    min: 2,
    tipo: "mensaje",
    lumiGrande: "hola",
    titulo: "¡Hola! Soy Lumi",
    bajada: "Hoy votamos con los dedos",
    chips: [
      { e: "☝️", t: "1 dedo" },
      { e: "✌️", t: "2 dedos" },
      { e: "🤟", t: "3 dedos" },
    ],
    nota: [
      "Presentar a Lumi: una búha guardiana que aparece cuando hay algo importante.",
      "Cómo votamos: cuando haya opciones 1, 2 o 3, levantan esa cantidad de dedos. Practicar: «¿quién vino a la sesión pasada? Un dedo sí, dos dedos no».",
      "Si hay niñas nuevas que no vinieron a la sesión 1, no pasa nada: el repaso de la siguiente slide las pone al día.",
    ],
    preguntar: ["¿Quién vino a la sesión pasada? ☝️ sí · ✌️ no"],
  },
  {
    id: "repaso",
    bloque: 1,
    tema: "coral",
    min: 4,
    tipo: "pregunta",
    eyebrow: "Repaso relámpago",
    situacion: "«🚨 Tu cuenta será eliminada. Tienes 10 minutos. Mándame el código que te llegó».",
    titulo: "¿Qué aprendimos a hacer?",
    opciones: ["Mandar el código rápido", "Para, piensa, verifica", "Reenviarlo a mis amigas"],
    correcta: 1,
    explica: "Si te apuran, asustan o emocionan: detente.",
    nota: [
      "Único guiño a la sesión 1: activa lo que ya saben sin volver a explicarlo.",
      "Pedir que alguien que vino le explique a las nuevas qué significa PARA · PIENSA · VERIFICA (en 30 segundos).",
      "Puente: «ya saben reconocer las trampas. Hoy vamos un paso más allá: qué revelamos sin darnos cuenta y qué herramientas tenemos».",
    ],
    respuesta: "2 · Para, piensa, verifica.",
  },
  {
    id: "acuerdos",
    bloque: 1,
    tema: "rosa",
    min: 7,
    tipo: "tarjetas",
    titulo: "Nuestros acuerdos",
    items: [
      { e: "🤫", k: "Lo que se dice aquí", v: "se queda aquí" },
      { e: "🙊", k: "Sin nombres reales", v: "decimos «una amiga»" },
      { e: "💜", k: "No hay preguntas tontas", v: "todas valen" },
      { e: "✋", k: "Puedo pasar", v: "si no quiero hablar" },
    ],
    nota: [
      "Leer cada acuerdo y pedir un pulgar arriba.",
      "PROTOCOLO: si una niña cuenta algo que suena a riesgo real (acoso fuerte, alguien que le ofrece dinero o encuentros, amenazas), NO profundizar frente al grupo. Agradecer, decir «hablemos al final» y hacerlo en privado. Luego informar a quien organiza para activar la ruta (orientación del colegio, Línea 141 ICBF, 123 si hay peligro inmediato).",
    ],
  },
  {
    id: "hoy",
    bloque: 1,
    tema: "turquesa",
    min: 9,
    tipo: "mensaje",
    emoji: "🧰",
    titulo: "Hoy: herramientas de guardiana",
    chips: [
      { e: "🔍", t: "Lo que revelas" },
      { e: "🚫", t: "Ofertas trampa" },
      { e: "🙈", t: "Poderes secretos" },
      { e: "📧", t: "Alias" },
      { e: "🎮", t: "Juegos" },
    ],
    revelar: true,
    nota: [
      "Mapa de la sesión. Revelar un chip por clic y decir una frase de cada uno.",
      "Generar expectativa con los alias: «les voy a enseñar un truco de correo que casi ningún adulto conoce».",
    ],
  },
  {
    id: "foto-detective",
    bloque: 1,
    tema: "violeta",
    min: 10,
    tipo: "publicacion",
    titulo: "¿Qué sabe un extraño de esta foto?",
    usuario: "vale.dibuja",
    lugar: "📍 Parque El Tunal",
    escena: ["🌳", "👧🏽", "🏫", "🐶", "🏠"],
    texto: "Saliendo del cole como todos los días a las 3 😎 con Lupe 🐶",
    pistas: [
      { t: "Uniforme y escudo: dónde estudias", x: 36, y: 44 },
      { t: "Ubicación etiquetada", x: 70, y: 9 },
      { t: "Rutina: todos los días a las 3", x: 88, y: 88 },
      { t: "Fachada y número de tu casa", x: 82, y: 48 },
      { t: "Nombre de tu mascota: ¡pregunta de seguridad!", x: 60, y: 62 },
    ],
    nota: [
      "Actividad de detective. Ellas dicen qué pistas ven; por cada una, clic y aparece el pin.",
      "Con estas 5 pistas, un desconocido sabe dónde estudias, a qué hora sales, por dónde pasas y dónde vives. Nadie te preguntó nada: lo publicaste tú.",
      "La mascota sorprende: muchas cuentas usan «¿nombre de tu primera mascota?» para recuperar la contraseña.",
    ],
    preguntar: ["¿Qué sabe de ti alguien que ve solo esta foto?"],
    respuesta: "Colegio (uniforme), ubicación, horario, dónde vive (fachada), nombre de la mascota.",
  },
  {
    id: "antes-de-publicar",
    bloque: 1,
    tema: "amarillo",
    min: 16,
    tipo: "tarjetas",
    titulo: "Antes de publicar, revisa",
    revelar: true,
    items: [
      { e: "👕", k: "Uniforme", v: "sin escudo ni nombre del colegio" },
      { e: "📍", k: "Ubicación", v: "apagada, nunca en vivo" },
      { e: "⏰", k: "Publica después", v: "cuando ya te fuiste" },
      { e: "🏠", k: "El fondo", v: "sin fachada, placas ni direcciones" },
      { e: "🔁", k: "Sin rutinas", v: "no digas «todos los días»" },
    ],
    nota: [
      "No se trata de dejar de publicar, sino de publicar sin regalar el mapa.",
      "La idea más útil: publicar DESPUÉS. La foto del parque se sube cuando ya estás en casa.",
      "Las historias «en vivo» con ubicación son las más riesgosas: dicen dónde estás ahora mismo.",
    ],
    preguntar: ["¿Cuál de estas nunca habías pensado?"],
  },
  {
    id: "ofertas",
    bloque: 1,
    tema: "noche",
    min: 19,
    tipo: "mensaje",
    emoji: "🎁",
    titulo: "Ofertas demasiado buenas",
    bajada: "Una trampa nueva que está pasando cerca",
    lumi: { pose: "alerta", t: "¡Ojos de búha!" },
    nota: [
      "Cambio de tono: la slide se oscurece a propósito.",
      "Presentar el caso como ficticio pero basado en algo real que está pasando en Bogotá.",
      "Hablar despacio y sin dramatismo: el objetivo es que reconozcan el patrón, no asustarlas.",
    ],
  },
  {
    id: "oferta-belleza",
    bloque: 1,
    tema: "noche",
    min: 21,
    tipo: "chat",
    titulo: "Caso: la oferta de belleza",
    bajada: "Encuentra las 🚩",
    contacto: { nombre: "glow.studio.bog ✨", e: "💇‍♀️" },
    mensajes: [
      { t: "Hola linda 💕 buscamos niñas para una campaña de cabello", pista: "Te buscan sin conocerte" },
      { t: "Te pagamos $100.000 y las uñas gratis 💅", pista: "Dinero fácil" },
      { t: "Es HOY, los cupos se acaban 🔥", pista: "Prisa" },
      { t: "Ven sola, es rapidito, no traigas a nadie", pista: "¡Que vayas SOLA!" },
      { t: "No le digas a tu mamá, es sorpresa 🤫 ¿En qué barrio vives?", pista: "Secreto + dónde vives" },
    ],
    nota: [
      "CASO FICTICIO basado en una modalidad real reportada en Bogotá en septiembre de 2026: a niñas y adolescentes les ofrecían por redes sociales dinero por cortarse el cabello y hacerse las uñas, y terminaban retenidas.",
      "Leer el chat completo. Por cada alarma que identifiquen, clic y aparece la bandera.",
      "Las dos más graves: que vayas SOLA y que no le cuentes a tu familia. Una oferta de trabajo o belleza de verdad nunca pide eso, y menos a una menor de edad.",
      "Conectar con la sesión 1: es el mismo patrón (confianza, secreto, aislamiento, presión) pero ahora lleva a un encuentro en persona.",
    ],
    preguntar: ["¿Qué pista te parece más peligrosa?", "¿Qué haría una empresa de verdad?"],
    respuesta: "Las 5 son alertas. Una empresa real habla con tus papás, no te apura, no te pide ir sola ni guardar secretos.",
  },
  {
    id: "dato-real",
    bloque: 1,
    tema: "noche",
    min: 27,
    tipo: "dato",
    cifra: "334",
    titulo: "niñas de 10 a 17 años",
    bajada: "fueron reportadas como desaparecidas en Bogotá entre enero y junio de 2026",
    detalle: "A muchas las contactan por redes con ofertas de dinero, belleza o trabajo.",
    fuente: "Policía Nacional y Medicina Legal, vía Semana (15-09-2026) · Noticias RCN (16-09-2026)",
    nota: [
      "Leer la cifra y dejar un silencio.",
      "Contexto para quien facilita: en el mismo periodo se reportaron 144 víctimas de trata en Bogotá, más del doble que en 2025. La cifra de 334 es de reportes de desaparición: muchas niñas aparecen, pero cada caso se toma en serio.",
      "Cerrar con poder, no con miedo: «esto no significa que no puedan salir o usar redes. Significa que ahora saben reconocer la trampa y tienen reglas para protegerse. Vamos a verlas».",
      "Si alguna se ve afectada o menciona un caso cercano: protocolo de la slide de acuerdos.",
    ],
  },
  {
    id: "regla-encuentros",
    bloque: 1,
    tema: "amarillo",
    min: 29,
    tipo: "regla",
    titulo: "La regla de los encuentros",
    pasos: [
      { e: "🙅‍♀️", k: "NUNCA SOLA", v: "con alguien de internet" },
      { e: "🗣️", k: "TU ADULTO", v: "sabe y te acompaña" },
      { e: "📍", k: "UBICACIÓN", v: "compartida con tu familia" },
      { e: "🔑", k: "PALABRA CLAVE", v: "secreta, en familia" },
    ],
    nota: [
      "Revelar una por una.",
      "Ubicación en tiempo real: WhatsApp y los celulares permiten compartirla con tu mamá o papá mientras vas a algún lado.",
      "Palabra clave familiar: una palabra secreta que solo sabe tu familia. Si alguien dice «tu mamá me mandó a recogerte», le pides la palabra. Si no la sabe, no vas. Proponer que la acuerden esta semana en casa (sin decirla aquí).",
      "Tarea para la casa: acordar la palabra clave. Queda en «Mi plan de guardiana» al final.",
    ],
    preguntar: ["¿Qué palabra clave sería difícil de adivinar? (no la digan en voz alta)"],
  },
  {
    id: "oferta-o-trampa",
    bloque: 1,
    tema: "coral",
    min: 33,
    tipo: "semaforo",
    titulo: "¿Oferta o trampa?",
    items: [
      { t: "Tu tía te lleva a cortarte el cabello a su peluquería", color: "verde" },
      { t: "Una marca que sigues sortea un premio: solo hay que seguirla", color: "amarillo" },
      { t: "Te ofrecen dinero por fotos o videos tuyos", color: "rojo" },
      { t: "Una «agencia» te invita a un casting: ve sola", color: "rojo" },
      { t: "Te ofrecen trabajo fácil por mensaje directo", color: "rojo" },
      { t: "Te regalan recargas si se ven en persona", color: "rojo" },
    ],
    nota: [
      "Leer cada situación, que digan el color en voz alta, clic para revelar.",
      "El sorteo es amarillo: puede ser real, pero verifica que sea la cuenta oficial y nunca des datos personales, dirección ni contraseñas para «reclamar el premio».",
      "Regla simple: si la oferta involucra dinero, tu cuerpo, tu imagen o encontrarse en persona, es rojo hasta que un adulto lo revise.",
    ],
    respuesta: "🟢 · 🟡 · 🔴 · 🔴 · 🔴 · 🔴",
  },
  {
    id: "poderes",
    bloque: 1,
    tema: "rosa",
    min: 38,
    tipo: "mensaje",
    emoji: "🦸‍♀️",
    titulo: "Poderes secretos contra el acoso",
    bajada: "Más allá de bloquear",
    lumi: { pose: "feliz", t: "¡Casi nadie los conoce!" },
    nota: [
      "Transición. Ya saben bloquear y reportar (sesión 1). Ahora: herramientas que funcionan cuando bloquear no alcanza o empeora las cosas.",
    ],
  },
  {
    id: "poderes-instagram",
    bloque: 1,
    tema: "turquesa",
    min: 39,
    tipo: "app",
    titulo: "Poderes que casi nadie usa",
    app: "Instagram · TikTok",
    pasos: [
      { e: "🙈", k: "Restringir", v: "no sabe que lo hiciste; sus comentarios solo los ve él" },
      { e: "🔤", k: "Palabras ocultas", v: "esconde comentarios con insultos" },
      { e: "🚧", k: "Limitar", v: "frena un ataque por unos días" },
      { e: "🏷️", k: "Etiquetas y menciones", v: "solo personas que sigues" },
      { e: "🔇", k: "Silenciar", v: "dejas de verlo sin que se entere" },
    ],
    nota: [
      "Cada clic enciende un interruptor en el celular de la pantalla.",
      "⚠️ Los menús cambian con cada actualización. Recorrer las cinco rutas en un celular real la semana del taller y corregir aquí lo que se haya movido. En Instagram casi todas viven en el mismo sitio: Configuración y privacidad → «Cómo pueden interactuar otras personas contigo».",
      "1 · RESTRINGIR (Instagram). Para qué: el acosador es del salón y bloquearlo lo empeora, porque se da cuenta. Qué le pasa a él: sus comentarios solo los ve él, sus mensajes caen en solicitudes y deja de ver si estás en línea. Ruta corta: entrar a su perfil → ⋯ (arriba a la derecha) → Restringir. Ruta por ajustes: Configuración y privacidad → Cómo pueden interactuar otras personas contigo → Cuentas restringidas.",
      "2 · PALABRAS OCULTAS (Instagram). Ruta: Configuración y privacidad → Cómo pueden interactuar otras personas contigo → Palabras ocultas. Activar «Ocultar comentarios ofensivos» y, más abajo, «Palabras y frases personalizadas»: ahí escriben sus propios apodos ofensivos, separados por comas. Vale también para las solicitudes de mensajes. En TikTok: Configuración y privacidad → Privacidad → Comentarios → Filtrar palabras clave.",
      "3 · LIMITAR (Instagram). Para qué: de un día para otro llegan muchos comentarios y mensajes de cuentas desconocidas. Ruta: Configuración y privacidad → Cómo pueden interactuar otras personas contigo → Limitar interacciones → escoger «cuentas que no te siguen» y/o «cuentas nuevas», y por cuánto tiempo. Es temporal: se apaga solo.",
      "4 · ETIQUETAS Y MENCIONES (Instagram). Ruta: Configuración y privacidad → Cómo pueden interactuar otras personas contigo → Etiquetas y menciones → dejar las dos en «Personas a las que sigues». En TikTok: Privacidad → Menciones y etiquetas. Extra de TikTok: Privacidad → Dúo y Privacidad → Stitch, para que nadie use sus videos.",
      "5 · SILENCIAR (Instagram). Para qué: no quieres verla, pero no quieres bloquear. Ruta: su perfil → botón «Siguiendo» → Silenciar → publicaciones e historias. Ella no se entera nunca.",
      "Cerrar sin agobiar: no hay que activar las cinco hoy. En el plan de guardiana cada una elige UNA para esta semana.",
    ],
    preguntar: ["¿Cuándo sería mejor restringir que bloquear?"],
    respuesta: "Cuando bloquear haría que la persona se dé cuenta y lo empeore (por ejemplo, alguien del salón).",
  },
  {
    id: "captura",
    bloque: 1,
    tema: "violeta",
    min: 44,
    tipo: "pregunta",
    eyebrow: "Quiz",
    situacion: "Alguien te insulta en un comentario. Quieres guardar la prueba.",
    titulo: "¿Qué captura sirve?",
    opciones: ["Solo el insulto, recortado", "Usuario + fecha + mensaje completo", "Le cuento a mi amiga qué decía"],
    correcta: 1,
    explica: "Captura que sirve = quién · cuándo · qué dijo.",
    nota: [
      "En la sesión 1 aprendieron a GUARDAR evidencia. Hoy: cómo hacerla bien.",
      "Una captura recortada no sirve: no se sabe quién lo dijo ni cuándo. Debe verse el nombre de usuario (idealmente abrir el perfil y capturarlo también), la fecha y el mensaje completo.",
      "Tips: capturar ANTES de bloquear (después ya no se ve), guardar las capturas en una carpeta, y si es posible copiar el enlace del perfil.",
    ],
    respuesta: "2 · Usuario + fecha + mensaje completo.",
  },
  {
    id: "suplantacion",
    bloque: 1,
    tema: "coral",
    min: 47,
    tipo: "escenario",
    eyebrow: "¿Qué harías tú?",
    titulo: "Una cuenta falsa con tu nombre",
    situacion: "Aparece @vale.dibuja_ con tus fotos. Le escribe cosas feas a tus amigas como si fueras tú.",
    opciones: [
      { t: "Le escribo a la cuenta falsa para que la borre", pasa: "No la borra y ahora sabe que te afecta 😟" },
      { t: "Me creo otra cuenta para contestarle", pasa: "Ahora hay tres cuentas peleando 🔥" },
      { t: "Capturas, la reporto como suplantación, aviso que no soy yo y le cuento a un adulto", pasa: "Tus amigas la reportan contigo y la app la baja 💪", ok: true },
    ],
    nota: [
      "Suplantación fue un concepto de la sesión 1; hoy vemos cómo se soluciona.",
      "Pasos: 1) capturas del perfil falso y de los mensajes, 2) reportar la cuenta con la opción «se hace pasar por mí» (las apps tienen esa opción específica), 3) pedir a amigas y familia que también la reporten, 4) publicar en tu cuenta real «esa cuenta no soy yo», 5) contárselo a un adulto.",
      "Si publica fotos íntimas o amenazas, es delito: se denuncia en el CAI Virtual.",
    ],
    preguntar: ["¿Quién más puede ayudarte a reportarla?"],
    respuesta: "3 · Capturas, reportar como suplantación, avisar que no eres tú, contarle a un adulto.",
  },
  {
    id: "resumen-1",
    bloque: 1,
    tema: "amarillo",
    min: 52,
    tipo: "mensaje",
    emoji: "{escudo}",
    titulo: "Lo que ya tienes",
    chips: [
      { e: "📸", t: "Publico después" },
      { e: "🙅‍♀️", t: "Nunca sola" },
      { e: "🔑", t: "Palabra clave" },
      { e: "🙈", t: "Restringir" },
      { e: "🧾", t: "Captura que sirve" },
    ],
    revelar: true,
    nota: [
      "Repaso rápido del bloque: ellas dicen el siguiente antes de revelarlo.",
      "Anunciar lo que viene: después de la pausa, trucos pro (alias de correo, juegos y contraseñas).",
    ],
  },
  {
    id: "pausa",
    bloque: 1,
    tema: "turquesa",
    min: 55,
    tipo: "pausa",
    titulo: "¡Pausa!",
    minutos: 10,
    bajada: "Estira, toma agua y vuelve con energía",
    // Música de fondo (en bucle, con fundido) y campana del último minuto.
    // Solo suenan en la ventana del proyector. Si falta un archivo, se salta.
    // Orden: de lo más tranquilo a lo más movido (3 × ~3 min ≈ 9 min, así la
    // campana cae justo al acabar la tercera). `vol` iguala volúmenes: la
    // acústica viene ~7 dB más baja que las otras dos.
    musica: [
      { src: "audio/Paper_Planes_Over_Water.mp3", vol: 1 },  // pop acústico
      { src: "audio/Notes_in_Sunlight.mp3", vol: 0.45 },     // lofi chill
      { src: "audio/Tomorrow_in_Motion.mp3", vol: 0.45 },    // pop electrónico suave
    ],
    // campana.mp3 es una pieza larga: se toca solo un trozo. Ajustar de oído
    // `desde` (segundo donde entra la marimba) y `dura` (cuánto suena).
    campana: { src: "audio/campana.mp3", desde: 4, dura: 10 },
    nota: [
      "La cuenta regresiva y la música arrancan solas al llegar a esta slide. Cuando falta un minuto suena una campanita: es la señal para volver a sus puestos. La música se apaga sola al terminar o al pasar de slide. Revisar el volumen del computador antes del taller.",
      "Durante la pausa: acercarse a quien se vio afectada durante el caso de la oferta de belleza, sin forzar.",
      "Repartir papelitos para el buzón de preguntas anónimas y una hoja o tarjeta para «Mi plan de guardiana».",
    ],
  },

  /* ═══════════════════════ BLOQUE 2 ═══════════════════════ */
  {
    id: "mision",
    bloque: 2,
    tema: "violeta",
    min: 65,
    tipo: "mensaje",
    emoji: "🕵️‍♀️",
    titulo: "Trucos de guardiana",
    bajada: "Lo que casi nadie sabe hacer",
    lumi: { pose: "hola", t: "¡A practicar!" },
    nota: [
      "El buzón de preguntas anónimas está abierto todo el bloque.",
      "Recordar que todo lo que vemos se practica en casa CON su adulto de confianza: se llevan la lista en «Mi plan de guardiana».",
    ],
  },
  {
    id: "alias",
    bloque: 2,
    tema: "turquesa",
    min: 66,
    tipo: "alias",
    titulo: "Tu correo tiene un superpoder",
    partes: [
      { t: "valentina", k: "tu correo" },
      { t: "+roblox", k: "el alias (lo que quieras)" },
      { t: "@gmail.com", k: "igual que siempre" },
    ],
    bajada: "Todo llega a tu MISMO correo 📬",
    nota: [
      "Gmail ignora lo que va después del signo +. Si tu correo es valentina@gmail.com, un mensaje a valentina+roblox@gmail.com te llega igual.",
      "El truco: al registrarte en cada app o juego, usas un alias distinto. valentina+roblox, valentina+tiktok, valentina+tienda.",
      "¿Para qué? Para saber QUIÉN te escribe de verdad, y detectar mentiras. Lo vemos en la siguiente slide.",
      "Revelar las tres partes con clic.",
    ],
    preguntar: ["¿Qué alias usarías para tu juego favorito?"],
  },
  {
    id: "bandeja",
    bloque: 2,
    tema: "amarillo",
    min: 70,
    tipo: "bandeja",
    titulo: "¿A qué alias llegó?",
    correos: [
      { de: "Roblox", asunto: "Tu código de verificación", para: "+roblox", veredicto: "✅ Coincide: es real", tono: "ok" },
      { de: "Instagram", asunto: "🚨 Tu cuenta será bloqueada en 10 min", para: "+roblox", veredicto: "🚨 ¡Trampa! Instagram no conoce ese alias", tono: "mal" },
      { de: "TikTok", asunto: "🎁 Ganaste 1.000 monedas", para: "+tiktok", veredicto: "🟡 Coincide, pero premio + prisa: verifica en la app", tono: "ojo" },
      { de: "SuperOfertas", asunto: "Promos solo para ti", para: "+tiktok", veredicto: "🕵️ Filtración: alguien compartió tu correo", tono: "info" },
    ],
    nota: [
      "Juego: para cada correo, ¿es real o trampa? Mirar SIEMPRE el «para». Clic revela el veredicto de cada fila.",
      "Correo 2: dice ser de Instagram pero llegó al alias de Roblox. Instagram nunca tuvo ese correo, así que es phishing seguro.",
      "Correo 3: el alias coincide, pero premio y prisa siguen siendo señales. Nunca entres por el enlace: abre la app directamente.",
      "Correo 4: una tienda que nunca conociste escribe al alias de TikTok. Ese correo se filtró o se vendió. Ya sabes de dónde salió.",
    ],
    preguntar: ["¿Real o trampa? ☝️ real · ✌️ trampa"],
    respuesta: "Real · Trampa · Verifica en la app · Filtración",
  },
  {
    id: "alias-pasos",
    bloque: 2,
    tema: "rosa",
    min: 77,
    tipo: "tarjetas",
    titulo: "Úsalo en 3 pasos",
    revelar: true,
    items: [
      { e: "✍️", k: "1. Regístrate", v: "tunombre+app@gmail.com" },
      { e: "📒", k: "2. Anota", v: "qué alias usaste en cada app" },
      { e: "👀", k: "3. Mira el «para»", v: "si no coincide, es trampa" },
      { e: "🧑‍🧒", k: "Con tu adulto", v: "configúralo juntos" },
    ],
    nota: [
      "Detalles para quien facilita:",
      "- Funciona en Gmail y en Outlook. Algunas páginas no aceptan el signo +: en ese caso se usa el correo normal.",
      "- El alias no esconde tu correo real: quien conozca el truco puede quitar el «+algo». Sirve para detectar y filtrar, no para esconderte.",
      "- Bonus: en Gmail se puede crear un filtro que mande todo lo de «+roblox» a una etiqueta.",
      "- Las cuentas de Google para menores de cierta edad se crean y administran con un adulto (Family Link). Por eso este truco se hace en casa, con su adulto.",
    ],
  },
  {
    id: "enlace-detective",
    bloque: 2,
    tema: "coral",
    min: 80,
    tipo: "pregunta",
    eyebrow: "Detective de enlaces",
    situacion: "«🎁 Roblox: reclama tus 1.000 robux gratis aquí 👉»",
    titulo: "¿Cuál enlace es de verdad Roblox?",
    opciones: ["roblox.com.robux-gratis.co/premio", "rob1ox.com/robux", "www.roblox.com/robux"],
    correcta: 2,
    explica: "El dueño del enlace es lo que va justo antes de la primera «/». Léelo de atrás hacia adelante.",
    nota: [
      "Escribir o señalar los tres enlaces despacio. Votan con los dedos y se revela.",
      "1 · roblox.com.robux-gratis.co: empieza con «roblox.com», pero lo que manda es el FINAL antes de la primera barra: «robux-gratis.co». El dueño es otra persona. Es la trampa más usada.",
      "2 · rob1ox.com: cambiaron la l por un 1. Otras letras gemelas: 0 y o, rn y m, I mayúscula y l.",
      "3 · www.roblox.com/robux: antes de la primera barra dice roblox.com. Es el real. Aun así, «robux gratis» sigue siendo señal de trampa: el enlace real no vuelve real la oferta.",
      "Truco para quien facilita: en la barra se lee de derecha a izquierda desde la primera «/»: .com → roblox. Lo que va a la izquierda de eso (www., premios., etc.) lo pone el mismo dueño.",
    ],
    preguntar: ["¿Cuál es el de verdad? ☝️ ✌️ 🤟"],
    respuesta: "3 · www.roblox.com. El 1 es de «robux-gratis.co» y el 2 cambió la l por un 1.",
  },
  {
    id: "trucos-correo",
    bloque: 2,
    tema: "turquesa",
    min: 83,
    tipo: "tarjetas",
    titulo: "Más trucos contra correos trampa",
    revelar: true,
    items: [
      { e: "👆", k: "Mantén presionado", v: "ves a dónde va el enlace sin abrirlo" },
      { e: "🔎", k: "Busca al dueño", v: "lo que va antes de la primera «/»" },
      { e: "📱", k: "Abre la app, no el enlace", v: "si es real, allá también aparece" },
      { e: "📬", k: "Pregúntale a Instagram", v: "«Correos recientes» muestra los que sí son suyos" },
    ],
    nota: [
      "1 · MANTENER PRESIONADO: en el celular, dejar el dedo sobre el enlace (sin soltar rápido) muestra la dirección completa sin abrirla. En computador basta con pasar el mouse por encima y mirar la esquina de abajo.",
      "2 · EL DUEÑO: lo que acaban de practicar en el quiz.",
      "3 · ABRIR LA APP: si el correo dice «tu cuenta será bloqueada» o «ganaste un premio», cerrar el correo y abrir la app o el juego directamente. Si es verdad, el aviso también está ahí adentro.",
      "4 · CORREOS RECIENTES (Instagram): Configuración y privacidad → Centro de cuentas → Contraseña y seguridad → Correos recientes. Ahí aparecen los correos que Instagram de verdad te mandó en los últimos días (de seguridad y de inicio de sesión). Si el correo que te asustó no está en esa lista, no es de Instagram. ⚠️ Verificar la ruta en un celular real la semana del taller: Meta la mueve seguido.",
      "Conectar con el alias: el alias dice a QUIÉN le diste el correo; estos trucos dicen si el correo es de quien dice ser.",
    ],
    preguntar: ["¿Cuál de estos van a probar primero?"],
  },
  {
    id: "lupa-fotos",
    bloque: 2,
    tema: "violeta",
    min: 86,
    tipo: "tarjetas",
    titulo: "¿Esa foto es de verdad suya?",
    revelar: true,
    items: [
      { e: "👆", k: "1. Mantén presionada la foto", v: "o hazle captura" },
      { e: "🔍", k: "2. «Buscar con Google Lens»", v: "Google busca dónde más aparece" },
      { e: "🚨", k: "3. ¿Sale con otro nombre?", v: "perfil falso: no le escribas más" },
      { e: "🪞", k: "Bonus: busca TUS fotos", v: "y mira si alguien las está usando" },
    ],
    nota: [
      "En la sesión 1 aprendieron a sospechar de perfiles falsos. Hoy: cómo comprobarlo en 10 segundos.",
      "Cómo se hace: en Android, mantener presionada la foto en Chrome o en la app de Google → «Buscar con Google Lens». En iPhone: abrir la app de Google → ícono de la cámara (Lens) → escoger la captura de la foto de perfil. También sirve images.google.com desde un computador.",
      "Qué buscar: si la misma foto aparece en otra cuenta con otro nombre, en una página de modelos o en un banco de fotos, ese perfil robó la foto. La «niña de 13 años» que te escribe puede ser cualquiera.",
      "Bonus: buscar sus propias fotos de perfil sirve para descubrir cuentas que las suplantan (conecta con el caso de @vale.dibuja_ del bloque 1).",
      "Si NO aparece nada, no significa que sea real: solo que esa foto no está publicada en otro lado. La duda sigue: nunca sola, siempre con tu adulto.",
    ],
    preguntar: ["¿A quién le harían esta prueba?"],
  },
  {
    id: "juegos",
    bloque: 2,
    tema: "noche",
    min: 89,
    tipo: "mensaje",
    emoji: "🎮",
    titulo: "Juega segura",
    bajada: "Roblox · Free Fire · Minecraft · Fortnite",
    nota: [
      "Preguntar rápido quién juega y a qué. Aterrizar los ejemplos al juego que más salga.",
      "En la sesión 1 vieron el caso del amigo del juego. Hoy: cómo se configura el juego para que ese caso no pueda pasar, y qué hacer cuando algo ya salió mal.",
    ],
    preguntar: ["¿Quién juega? ¿A qué?"],
  },
  {
    id: "roblox-escudo",
    bloque: 2,
    tema: "turquesa",
    min: 90,
    tipo: "app",
    titulo: "Tu juego en modo escudo",
    app: "Roblox (y parecidos)",
    pasos: [
      { e: "💬", k: "Chat solo con amigos", v: "o apagado" },
      { e: "🎙️", k: "Chat de voz apagado", v: "" },
      { e: "👥", k: "Quién te invita", v: "solo amigos" },
      { e: "📩", k: "Mensajes privados", v: "nadie o amigos" },
      { e: "🔐", k: "Verificación en 2 pasos", v: "contra robos" },
      { e: "🔢", k: "Controles parentales", v: "con tu adulto" },
    ],
    nota: [
      "Cada clic enciende un interruptor.",
      "Roblox: Configuración → Privacidad (quién puede chatear, invitarme, unirse a mí) y Seguridad → Verificación en dos pasos. Los controles parentales se manejan desde la cuenta del papá o la mamá vinculada.",
      "Free Fire y Fortnite tienen opciones parecidas (chat de voz, solicitudes de amistad, controles parentales de Epic). Minecraft: jugar en servidores de amigos o en realms privados.",
      "Los menús cambian seguido: revisarlos antes del taller.",
    ],
  },
  {
    id: "reglas-juego",
    bloque: 2,
    tema: "amarillo",
    min: 95,
    tipo: "tarjetas",
    titulo: "Las 4 reglas del juego",
    revelar: true,
    items: [
      { e: "🎁", k: "Regalo = trampa", v: "robux, diamantes y pases gratis crean deuda" },
      { e: "🚪", k: "El chat se queda en el juego", v: "no pasar a WhatsApp ni Discord" },
      { e: "🙊", k: "Tu info no juega", v: "nombre real, colegio y fotos, fuera" },
      { e: "🛒", k: "Solo la tienda oficial", v: "nunca compres cuentas ni skins afuera" },
    ],
    nota: [
      "Regalo = trampa: quien te regala algo después pide algo a cambio. «Te regalé robux, ahora me debes una foto».",
      "Pasar a WhatsApp o Discord saca la conversación de donde el juego puede moderarla. Es la señal más típica.",
      "Comprar cuentas, skins o monedas fuera de la tienda oficial es la estafa más común: pagas y no te llega nada, o te roban la cuenta.",
    ],
    preguntar: ["¿Alguna vez alguien les ha ofrecido regalos en un juego?"],
  },
  {
    id: "cuenta-hackeada",
    bloque: 2,
    tema: "violeta",
    min: 99,
    tipo: "escenario",
    eyebrow: "¿Qué harías tú? · Juegos 1",
    titulo: "Te robaron la cuenta del juego",
    situacion: "Ya no puedes entrar. Tus amigos dicen que «tú» les estás pidiendo robux.",
    opciones: [
      { t: "Me creo otra cuenta y me olvido", pasa: "El ladrón sigue estafando con tu nombre 😟" },
      { t: "Le pago a alguien que dice que me la recupera", pasa: "Segunda estafa: pierdes dinero y la cuenta 💸" },
      { t: "Recuperación oficial, aviso a mis amigos y activo 2 pasos", pasa: "Recuperas tu cuenta y proteges a tus amigos {escudo}", ok: true },
    ],
    nota: [
      "Plan de rescate: 1) «¿Olvidaste tu contraseña?» desde la app o página oficial, 2) si no funciona, soporte oficial del juego (nunca «recuperadores» de redes), 3) avisar a tus amigos que no eres tú, 4) al recuperarla: cambiar contraseña, cerrar sesiones abiertas y activar la verificación en 2 pasos.",
      "Si usaste la misma contraseña en otras apps, cambiarla allá también.",
    ],
    respuesta: "3 · Recuperación oficial + avisar + 2 pasos.",
  },
  {
    id: "acoso-partidas",
    bloque: 2,
    tema: "rosa",
    min: 103,
    tipo: "escenario",
    eyebrow: "¿Qué harías tú? · Juegos 2",
    titulo: "Te persiguen en cada partida",
    situacion: "Un grupo te insulta por el chat y te sigue a cada servidor al que entras.",
    opciones: [
      { t: "Les contesto igual de feo", pasa: "Ellos buscan tu reacción: siguen 🔁" },
      { t: "Dejo de jugar para siempre", pasa: "No tienes que dejar lo que te gusta 😢" },
      { t: "Capturas, bloqueo, reporto en el juego y cambio a jugar solo con amigos", pasa: "Pierden su público y tú sigues jugando 🎮", ok: true },
    ],
    nota: [
      "Todos los juegos tienen botón de reportar y bloquear dentro de la partida.",
      "Cambiar la privacidad a «solo amigos» evita que te sigan a otros servidores.",
      "Si hay amenazas o te piden fotos: ya no es un tema del juego. Adulto de confianza y denuncia.",
    ],
    respuesta: "3 · Capturas, bloquear, reportar y jugar solo con amigos.",
  },
  {
    id: "contrasena",
    bloque: 2,
    tema: "violeta",
    min: 106,
    tipo: "contrasena",
    titulo: "Reto: contraseña superpoderosa",
    // `regla` la verifica app.js en vivo: el consejo se pone en verde al cumplirse
    consejos: [
      { t: "Una frase loca con mayúsculas", regla: "frase" },
      { t: "Números y símbolos", regla: "simbolos" },
      { t: "Más de 12 letras", regla: "largo" },
      { t: "Nada de años ni claves famosas", regla: "personal" },
    ],
    lumi: { pose: "alerta", t: "¡Nunca escribas aquí tu clave real!" },
    nota: [
      "Juego en vivo: ellas dictan contraseñas inventadas y se escriben en el recuadro. El medidor dice qué tan fuerte es y cuánto tardaría un computador en adivinarla.",
      "Se puede escribir desde la vista presentador: aparece igual en el proyector.",
      "Empezar con «sofia2013» (débil), luego «12345678», luego construir juntas una frase: «MiGato$ComeArepa3Veces».",
      "Conectar con la foto del bloque 1: el nombre de tu mascota o tu año de nacimiento no sirven como contraseña ni como respuesta de seguridad.",
      "Una contraseña distinta para cada app: si te roban una, no te roban todas.",
    ],
    preguntar: ["¡Díctenme una contraseña inventada!"],
  },
  {
    id: "quiz-clave",
    bloque: 2,
    tema: "coral",
    min: 111,
    tipo: "pregunta",
    eyebrow: "Quiz",
    titulo: "¿Cuál es más fuerte?",
    opciones: ["lupe2013", "12345678", "Unicornio!Come3Arepas"],
    correcta: 2,
    explica: "Larga, loca y con símbolos 🦄",
    nota: ["Rápido: votan y se revela. «lupe2013» es la mascota de la foto del bloque 1 más un año: se adivina con solo ver su perfil."],
    respuesta: "3 · Unicornio!Come3Arepas",
  },
  {
    id: "pregunta-seguridad",
    bloque: 2,
    tema: "amarillo",
    min: 113,
    tipo: "pregunta",
    eyebrow: "Truco de guardiana",
    situacion: "La app te pregunta: «¿Cómo se llamaba tu primera mascota?»",
    titulo: "¿Qué respondes?",
    opciones: ["Lupe", "Lupe2013", "Una mentira que solo tú sabes: «ArepaVoladora»"],
    correcta: 2,
    explica: "Es otra contraseña: no tiene que ser verdad 🤫",
    nota: [
      "Conectar con la foto del bloque 1: «Lupe» salía en la publicación de @vale.dibuja. Cualquiera que vio la foto puede responder la pregunta y recuperar SU cuenta.",
      "El truco: responder con una mentira que no se puede adivinar y anotarla en casa con su adulto (en la misma libreta de los alias, o en el gestor de contraseñas del celular de la familia).",
      "Lo mismo vale para «¿en qué colegio estudiaste?», «¿nombre de tu mejor amiga?», «¿ciudad donde naciste?»: todo eso está en tus redes.",
      "Extra: el correo o celular de recuperación de la cuenta debería ser el de su adulto, no el de una amiga.",
    ],
    respuesta: "3 · Una mentira secreta. Lupe y Lupe2013 se adivinan viendo la foto.",
  },
  {
    id: "whatsapp-escudo",
    bloque: 2,
    tema: "turquesa",
    min: 116,
    tipo: "app",
    titulo: "WhatsApp en modo escudo",
    app: "WhatsApp",
    pasos: [
      { e: "👥", k: "Grupos", v: "solo mis contactos me añaden" },
      { e: "🖼️", k: "Foto de perfil", v: "solo mis contactos" },
      { e: "📍", k: "Ubicación en tiempo real", v: "solo con mi familia" },
      { e: "🔐", k: "Verificación en 2 pasos", v: "PIN de 6 números" },
      { e: "📵", k: "Llamadas de desconocidos", v: "silenciadas" },
    ],
    nota: [
      "Grupos: Ajustes → Privacidad → Grupos → Mis contactos. Así no te meten a grupos de desconocidos (muy usado para acoso y para ofertas trampa).",
      "Ubicación en tiempo real: conecta con la regla de los encuentros. Se comparte desde el chat con tu mamá o papá: Adjuntar → Ubicación → Ubicación en tiempo real.",
      "Verificación en dos pasos: Ajustes → Cuenta. Evita que te roben la cuenta aunque alguien consiga el código por SMS.",
      "Llamadas de desconocidos: Ajustes → Privacidad → Llamadas → Silenciar llamadas de desconocidos. No suenan, pero quedan en la lista de llamadas: si era alguien conocido, lo ves después.",
    ],
  },
  {
    id: "sesiones",
    bloque: 2,
    tema: "violeta",
    min: 119,
    tipo: "sesiones",
    titulo: "¿Quién más tiene abierto tu WhatsApp?",
    app: "Dispositivos vinculados",
    dispositivos: [
      { e: "💻", k: "Google Chrome (Windows)", v: "Activo hace 5 min", intruso: true },
      { e: "🖥️", k: "Computador de casa", v: "Hoy, 7:10 a. m." },
    ],
    rutas: [
      { k: "WhatsApp", v: "Ajustes → Dispositivos vinculados" },
      { k: "Instagram", v: "Centro de cuentas → Contraseña y seguridad → Dónde iniciaste sesión" },
      { k: "Google", v: "Tu cuenta → Seguridad → Tus dispositivos" },
    ],
    nota: [
      "Situación para contar: «Una amiga del salón sabe cosas de tus chats que tú no le contaste». Muchas veces es que alguien abrió tu WhatsApp Web en un computador (del colegio, de un café internet, de una amiga) y nunca lo cerraste. Desde ahí lee TODO en vivo, y tú no ves ninguna alerta.",
      "Clic 1: aparece el intruso. Clic 2: se cierra esa sesión. Luego se revelan las rutas.",
      "WhatsApp: Ajustes → Dispositivos vinculados. Tocar el dispositivo que no reconoces → Cerrar sesión.",
      "Instagram: Configuración y privacidad → Centro de cuentas → Contraseña y seguridad → Dónde iniciaste sesión. Ahí se puede cerrar la sesión de cada celular o computador. Google: myaccount.google.com → Seguridad → Tus dispositivos.",
      "Después de cerrar una sesión extraña: cambiar la contraseña y activar la verificación en 2 pasos (la de la slide anterior).",
      "Hábito: revisarlo una vez al mes con su adulto, y SIEMPRE cerrar sesión cuando usen un computador que no es suyo.",
      "⚠️ Verificar nombres de menús en un celular real la semana del taller.",
    ],
    preguntar: ["¿Alguna vez abrieron su WhatsApp o Instagram en un computador que no es suyo?"],
  },
  {
    id: "plan",
    bloque: 2,
    tema: "amarillo",
    min: 122,
    tipo: "plan",
    titulo: "Mi plan de guardiana",
    campos: [
      { e: "🧑‍🧒", k: "Mi adulto de confianza" },
      { e: "🔑", k: "Nuestra palabra clave", v: "(no la escribas: solo acuérdala)" },
      { e: "📧", k: "Mi alias para juegos", v: "tunombre+ ____ @gmail.com" },
      { e: "{escudo}", k: "Esta semana voy a activar" },
    ],
    nota: [
      "Cada una llena su tarjeta u hoja (se repartió en la pausa). 4 minutos.",
      "La palabra clave NO se escribe: se acuerda en casa. En la tarjeta solo marcan «pendiente» o «lista».",
      "En «voy a activar» eligen UNA cosa concreta: restringir, palabras ocultas, cuenta privada, chat solo amigos, 2 pasos, alias, respuesta de seguridad mentirosa, revisar dispositivos vinculados. Mejor una que sí hagan que cinco que no.",
      "Invitar a que muestren la tarjeta a su adulto hoy mismo.",
    ],
  },
  {
    id: "lineas",
    bloque: 2,
    tema: "turquesa",
    min: 127,
    tipo: "lineas",
    titulo: "Siempre hay ayuda",
    lineas: [
      { n: "141", k: "ICBF", v: "Gratis · 24 horas" },
      { n: "123", k: "Emergencias", v: "Policía · peligro ya" },
      { n: "155", k: "Línea Mujer", v: "Orientación · 24 horas" },
      { n: "🌐", k: "teprotejo.org", v: "Reporta contenido" },
      { n: "🚓", k: "CAI Virtual", v: "caivirtual.policia\u200b.gov.co" },
    ],
    nota: [
      "Solo recordatorio: las líneas se vieron en la sesión 1. Nuevas: 155.",
      "Aclarar para qué sirve cada una con un ejemplo de hoy: una oferta sospechosa de encuentro o alguien siguiéndote → 123. Una cuenta que se hace pasar por ti con amenazas → CAI Virtual. Contenido de niñas en redes → Te Protejo.",
      "Si el taller es en Bogotá, mencionar la Línea 106 (orientación para niñas, niños y adolescentes).",
    ],
  },
  {
    id: "buzon",
    bloque: 2,
    tema: "violeta",
    min: 129,
    tipo: "mensaje",
    emoji: "📮",
    titulo: "Buzón de preguntas",
    bajada: "Las leemos sin nombres",
    nota: [
      "Leer algunos papelitos en voz alta y responder.",
      "Si una pregunta revela una situación de riesgo, NO leerla: guardarla y seguir el protocolo.",
      "Si no alcanza el tiempo, prometer respuesta por medio de la fundación.",
    ],
  },
  {
    id: "cierre",
    bloque: 2,
    tema: "rosa",
    min: 132,
    tipo: "cierre",
    titulo: "¡Ya eres Guardiana Digital!",
    chips: [
      { e: "📸", t: "Publico después" },
      { e: "🙅‍♀️", t: "Nunca sola" },
      { e: "📧", t: "Uso alias" },
      { e: "🎮", t: "Juego segura" },
    ],
    nota: [
      "Las cuatro ideas de hoy, en voz alta, todas de pie.",
      "Agradecer. Foto grupal (sin publicar caras de niñas sin autorización de sus acudientes).",
      "Cerrar con la frase: «internet es una ciudad increíble, y ahora tienen las llaves para moverse en ella».",
    ],
  },
];
